#!/usr/bin/env python3
"""Battery C-rep analysis (pre-registered PLANO 2026-08-26 ~15:30): do three
independent consolidation lineages replicate the attract effect on a fresh,
never-consulted held-out set (heldout2, single final read)?

Primary: attract vs base (cycle 5 adapters) on heldout2 mean test excess.
Cells = 8 variants; per-variant differences AVERAGED over the 3 lineages;
exact paired sign-flip (2^8) + hierarchical bootstrap (lineages, then
variants). Secondary: attract vs random (same), best (two-sided), full
lineage x variant table, between-lineage spread (descriptive). The shared-pool
one-shot control (top vs rand vs base from one pool) is reported as registered.

Writes docs/APPENDIX_C_REP.md. --train-smoke tests the mechanics on TRAIN
cycle-5 pools only (never reads heldout2)."""
import itertools, json, sys
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
R = ROOT / "runs/dream_c_rep"
LIN = ["L1", "L2", "L3"]
ARMS = ["base", "attract", "random"]

def arm_variant_means(d):
    """candidates.json -> {variant: (mean test excess of valid, best, n_valid)}"""
    f = Path(d) / "candidates.json"
    if not f.exists(): return None
    by = {}
    for c in json.loads(f.read_text()).values():
        if c.get("ok"):
            by.setdefault(c["variant"], []).append(c["test"])
    return {v: (float(np.mean(xs)), float(np.min(xs)), len(xs)) for v, xs in by.items()}

def signflip(d, alt):
    d = np.asarray(d, float); n = len(d); obs = d.mean()
    if alt == "greater":
        c = sum(1 for sg in itertools.product((1, -1), repeat=n) if (d * np.array(sg)).mean() >= obs - 1e-12)
    elif alt == "less":
        c = sum(1 for sg in itertools.product((1, -1), repeat=n) if (d * np.array(sg)).mean() <= obs + 1e-12)
    else:
        c = sum(1 for sg in itertools.product((1, -1), repeat=n) if abs((d * np.array(sg)).mean()) >= abs(obs) - 1e-12)
    return obs, c / 2 ** n

def hier_boot(diffs_lv, n=10000, seed=0):
    """diffs_lv: (n_lineage, n_variant) matrix; resample lineages then variants."""
    rng = np.random.default_rng(seed)
    L, V = diffs_lv.shape
    out = np.empty(n)
    for i in range(n):
        li = rng.integers(0, L, L)
        vi = rng.integers(0, V, V)
        out[i] = diffs_lv[np.ix_(li, vi)].mean()
    return float(np.percentile(out, 2.5)), float(np.percentile(out, 97.5))

smoke = "--train-smoke" in sys.argv
cyc = "c5" if smoke else "c6"          # smoke reads TRAIN cycle-5 gens, never heldout2
which = "train pools (mechanics only)" if smoke else "heldout2 (single final read)"

M = {}   # M[lineage][arm] = {variant: (mean, best, n)}
for L in LIN:
    M[L] = {a: arm_variant_means(R / L / f"{a}_{cyc}") for a in ARMS}
    missing = [a for a, v in M[L].items() if not v]
    if missing:
        print(f"[{'smoke' if smoke else 'ABORT'}] {L}: missing {missing}")
        if not smoke: sys.exit(f"incomplete: {L} lacks {missing} at {cyc} — wait for C-REP-FIX DONE")

if smoke:
    LIN = [L for L in LIN if all(M[L][a] for a in ARMS)]
    print(f"[smoke] using complete lineages: {LIN}")
variants = sorted(set.intersection(*[set(M[L][a]) for L in LIN for a in ARMS if M[L][a]]))
print(f"reading {which}: {len(variants)} common variants")

def diff_matrix(a, b, key=0):
    return np.array([[M[L][a][v][key] - M[L][b][v][key] for v in variants] for L in LIN])

md = [f"# Appendix — Battery C-rep: three independent consolidation lineages "
      f"(auto-generated by scripts/analysis_c_rep.py{' --train-smoke' if smoke else ''})\n",
      f"Three lineages (fresh generation/selection seeds), five cycles fixed in advance, "
      f"read on {which}. mean = mean test excess of valid candidates (lower is better); "
      f"cells = variants ({len(variants)}), per-variant differences averaged over lineages; "
      f"exact sign-flip 2^{len(variants)}; hierarchical bootstrap (lineages, then variants).\n",
      "## Pre-registered tests\n",
      "| test | contrast | Δ (mean over lineages) [hier. CI] | p | per-lineage Δ | verdict |",
      "|---|---|---|---|---|---|"]

tests = [("CR1 (primary, one-sided <0)", "attract - base", "less", diff_matrix("attract", "base")),
         ("CR2 (one-sided <0)", "attract - random", "less", diff_matrix("attract", "random")),
         ("CR3 (two-sided, best)", "attract - base (best)", "two", diff_matrix("attract", "base", key=1))]
for name, contrast, alt, mat in tests:
    pervar = mat.mean(axis=0)
    obs, p = signflip(pervar, alt)
    lo, hi = hier_boot(mat)
    perlin = ", ".join(f"{mat[i].mean():+.4f}" for i in range(len(LIN)))
    ok = p <= 0.05
    md.append(f"| {name} | {contrast} | {obs:+.4f} [{lo:+.4f}, {hi:+.4f}] | {p:.4f} | {perlin} | "
              f"{'SUPPORTED' if ok else 'not supported'} |")

md.append("\n## Per-lineage arm means (over variants)\n")
md.append("| lineage | " + " | ".join(ARMS) + " |"); md.append("|---|---|---|---|")
for L in LIN:
    md.append(f"| {L} | " + " | ".join(f"{np.mean([M[L][a][v][0] for v in variants]):.4f}" for a in ARMS) + " |")

md.append("\n## Lineage x variant (attract - base)\n")
md.append("| variant | " + " | ".join(LIN) + " |"); md.append("|---|---|---|---|")
mat = diff_matrix("attract", "base")
for j, v in enumerate(variants):
    md.append(f"| {v} | " + " | ".join(f"{mat[i, j]:+.4f}" for i in range(len(LIN))) + " |")

# shared-pool control
pool = {a: arm_variant_means(R / "pool1" / f"{a}_{'c1' if smoke else 'c2'}") for a in ("base", "top", "rand")}
if all(pool.values()):
    pv = sorted(set.intersection(*[set(x) for x in pool.values()]))
    md.append("\n## Shared-pool one-shot control (registered; single lineage)\n")
    md.append("| arm | mean excess | best |"); md.append("|---|---|---|")
    for a in ("base", "top", "rand"):
        md.append(f"| {a} | {np.mean([pool[a][v][0] for v in pv]):.4f} | {np.mean([pool[a][v][1] for v in pv]):.4f} |")
    d = np.array([pool["top"][v][0] - pool["rand"][v][0] for v in pv])
    obs, p = signflip(d, "less")
    md.append(f"\ntop vs rand (same pool): {obs:+.4f}, p = {p:.4f} (one-sided, n = {len(pv)})")
else:
    md.append("\n(shared-pool control not yet available)")

out = "\n".join(md) + "\n"
print(out)
if not smoke:
    (ROOT / "docs/APPENDIX_C_REP.md").write_text(out); print("wrote docs/APPENDIX_C_REP.md")
