#!/usr/bin/env python3
"""Paper analysis: figures + appendix tables from the raw run data under runs/.

Reproducible: reads only what the experiments saved (judgment JSONs, novelty
JSONs, evolution histories) and writes docs/figures/*.png plus
docs/APPENDIX_ANALYSIS.md. Effect sizes (Cliff's delta), Mann-Whitney U,
bootstrap CIs, per-seed robustness, distributions, and the instrument
calibration are all produced here.

    python scripts/analysis.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
from creative_machine.stats import bootstrap_diff_ci  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
RUNS = ROOT / "runs"
FIG = ROOT / "docs" / "figures"
FIG.mkdir(parents=True, exist_ok=True)

# Validated categorical palette (dataviz skill; fixed order, never cycled)
PAL = {"scaffold0": "#2a78d6", "none": "#2a78d6", "abl_forget": "#eb6834", "abl_salience": "#1baf7a",
       "bare_reseed": "#eda100", "bare": "#4a3aa7", "plain": "#eb6834", "clock": "#1baf7a"}
LABEL = {"scaffold0": "DREAM scaffold (λ=0)", "none": "DREAM (λ>0)", "abl_forget": "salience+forgetting",
         "abl_salience": "salience only", "bare_reseed": "bare + clock reseed", "bare": "bare generation",
         "plain": "plain in loop (λ=0)", "clock": "clock review"}
SHORT = {"scaffold0": "DREAM\nscaffold", "abl_salience": "salience\nonly", "bare_reseed": "bare +\nclock reseed",
         "bare": "bare", "none": "DREAM", "plain": "plain", "clock": "clock", "abl_forget": "sal.+forget"}
DIMS = ("surprise", "connection", "coherence")

import matplotlib  # noqa: E402
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from scipy import stats as sps  # noqa: E402

plt.rcParams.update({"font.size": 9, "axes.spines.top": False, "axes.spines.right": False,
                     "axes.grid": True, "grid.alpha": 0.25, "grid.linewidth": 0.5})


def cliffs_delta(a, b) -> float:
    a, b = np.asarray(a), np.asarray(b)
    gt = sum((x > b).sum() for x in a)
    lt = sum((x < b).sum() for x in a)
    return float((gt - lt) / (len(a) * len(b)))


def compare(a, b) -> dict:
    lo, hi = bootstrap_diff_ci(a, b)
    u = sps.mannwhitneyu(a, b, alternative="two-sided")
    return {"mean_a": float(np.mean(a)), "mean_b": float(np.mean(b)), "ci": (lo, hi),
            "cliffs": cliffs_delta(a, b), "mw_p": float(u.pvalue), "n_a": len(a), "n_b": len(b)}


def load_json(p: Path):
    return json.loads(p.read_text()) if p.exists() else None


md: list[str] = ["# Appendix — analysis tables (auto-generated by scripts/analysis.py)\n"]


def table(title: str, header: list[str], rows: list[list]) -> None:
    md.append(f"\n### {title}\n")
    md.append("| " + " | ".join(header) + " |")
    md.append("|" + "---|" * len(header))
    for r in rows:
        md.append("| " + " | ".join(str(x) for x in r) + " |")


# ---------------------------------------------------------------- reverie: scaffold battery
sc = load_json(RUNS / "dream_scaffold" / "rejudge_surprise.json") or []
# abl_forget is text-identical to scaffold0 (re-encounter never fired): not a separate condition
conds_present = [c for c in ("scaffold0", "abl_salience", "bare_reseed", "bare")
                 if any(r["cond"] == c for r in sc)]
if sc:
    # Fig 1: distributions per condition per dimension (violin + points)
    fig, axes = plt.subplots(1, 3, figsize=(10, 3.2), sharey=True)
    for ax, dim in zip(axes, DIMS):
        data = [[r[dim] for r in sc if r["cond"] == c and r.get(dim) is not None] for c in conds_present]
        parts = ax.violinplot(data, showmeans=False, showextrema=False, widths=0.8)
        for body, c in zip(parts["bodies"], conds_present):
            body.set_facecolor(PAL[c]); body.set_alpha(0.25); body.set_edgecolor("none")
        for i, (d, c) in enumerate(zip(data, conds_present), start=1):
            jitter = (np.random.default_rng(0).random(len(d)) - 0.5) * 0.25
            ax.scatter(np.full(len(d), i) + jitter, d, s=9, color=PAL[c], alpha=0.8, linewidths=0)
            ax.hlines(np.mean(d), i - 0.3, i + 0.3, color=PAL[c], linewidth=2)
        ax.set_xticks(range(1, len(conds_present) + 1))
        ax.set_xticklabels([SHORT[c] for c in conds_present], fontsize=7)
        ax.set_title(dim); ax.set_ylim(-0.3, 10.3)
    axes[0].set_ylabel("judged score (0–10, median of k=5)")
    fig.suptitle("Reverie windows by condition — distributions (Opus 5 judge)", y=1.02)
    fig.tight_layout(); fig.savefig(FIG / "fig1_reverie_distributions.png", dpi=200, bbox_inches="tight"); plt.close(fig)

    rows = []
    for dim in DIMS:
        base = [r[dim] for r in sc if r["cond"] == "scaffold0" and r.get(dim) is not None]
        for c in conds_present:
            v = [r[dim] for r in sc if r["cond"] == c and r.get(dim) is not None]
            if c == "scaffold0":
                rows.append([dim, LABEL[c], len(v), f"{np.mean(v):.2f} ± {np.std(v):.2f}", "—", "—", "—"])
            else:
                cmp = compare(base, v)
                rows.append([dim, LABEL[c], len(v), f"{np.mean(v):.2f} ± {np.std(v):.2f}",
                             f"[{cmp['ci'][0]:+.2f}, {cmp['ci'][1]:+.2f}]", f"{cmp['cliffs']:+.2f}", f"{cmp['mw_p']:.3g}"])
    table("Reverie battery — scaffold vs each condition (unit = window)",
          ["dimension", "condition", "n", "mean ± sd", "scaffold − cond CI95", "Cliff's δ", "Mann-Whitney p"], rows)

    # Fig 2: surprise vs coherence scatter per condition (does surprise cost coherence?)
    fig, ax = plt.subplots(figsize=(4.6, 4))
    for c in conds_present:
        pts = [(r["surprise"], r["coherence"]) for r in sc if r["cond"] == c and r.get("surprise") is not None]
        if pts:
            x, y = zip(*pts)
            jx = (np.random.default_rng(1).random(len(x)) - 0.5) * 0.3
            jy = (np.random.default_rng(2).random(len(y)) - 0.5) * 0.3
            ax.scatter(np.array(x) + jx, np.array(y) + jy, s=16, color=PAL[c], alpha=0.75, label=LABEL[c], linewidths=0)
    ax.set_xlabel("surprise"); ax.set_ylabel("coherence"); ax.set_xlim(-0.5, 10.5); ax.set_ylim(-0.5, 10.5)
    ax.axhline(5, color="#999", lw=0.6, ls=":"); ax.axvline(5, color="#999", lw=0.6, ls=":")
    ax.legend(fontsize=7, frameon=False, loc="lower right"); ax.set_title("Surprise vs coherence per window")
    fig.tight_layout(); fig.savefig(FIG / "fig2_surprise_vs_coherence.png", dpi=200); plt.close(fig)

    # per-seed robustness: mean surprise per seed per condition
    seeds = sorted({r["cell"].split("_")[0] for r in sc})
    rows = []
    for s_ in seeds:
        row = [s_]
        for c in conds_present:
            v = [r["surprise"] for r in sc if r["cell"].startswith(s_ + "_") and r["cond"] == c and r.get("surprise") is not None]
            row.append(f"{np.mean(v):.2f} (n={len(v)})" if v else "—")
        rows.append(row)
    table("Per-seed mean surprise by condition (robustness)", ["seed"] + [LABEL[c] for c in conds_present], rows)
    # Fig 3: per-seed paired lines, scaffold vs bare
    if "bare" in conds_present:
        fig, ax = plt.subplots(figsize=(4.2, 3.4))
        for s_ in seeds:
            a = [r["surprise"] for r in sc if r["cell"] == f"{s_}_scaffold0" and r.get("surprise") is not None]
            b = [r["surprise"] for r in sc if r["cell"] == f"{s_}_bare" and r.get("surprise") is not None]
            if a and b:
                ax.plot([0, 1], [np.mean(b), np.mean(a)], color="#888", lw=0.8, alpha=0.7)
                ax.scatter([0, 1], [np.mean(b), np.mean(a)], color=[PAL["bare"], PAL["scaffold0"]], s=22, zorder=3, linewidths=0)
        ax.set_xticks([0, 1]); ax.set_xticklabels(["bare", "DREAM scaffold"]); ax.set_ylabel("mean surprise (per seed)")
        ax.set_title("Per-seed: bare → scaffold (surprise)"); fig.tight_layout()
        fig.savefig(FIG / "fig3_per_seed_scaffold_vs_bare.png", dpi=200); plt.close(fig)

    # windows over time: score vs step, per condition (does the loop improve or oscillate?)
    fig, ax = plt.subplots(figsize=(6.4, 3))
    for c in conds_present:
        pts = sorted((r["step"], r["surprise"]) for r in sc if r["cond"] == c and r.get("surprise") is not None)
        if pts:
            x, y = zip(*pts)
            ax.scatter(x, y, s=12, color=PAL[c], alpha=0.6, label=LABEL[c], linewidths=0)
    ax.set_xlabel("position in stream (tokens)"); ax.set_ylabel("surprise"); ax.legend(fontsize=7, frameon=False, ncol=2)
    ax.set_title("Reviewed windows along the stream"); fig.tight_layout()
    fig.savefig(FIG / "fig4_surprise_over_stream.png", dpi=200); plt.close(fig)

# ---------------------------------------------------------------- reverie: push vs plain vs clock (dream_def)
dd = load_json(RUNS / "dream_def" / "rejudge_surprise.json") or []
if dd:
    rows = []
    for dim in DIMS:
        base = [r[dim] for r in dd if r["cond"] == "none" and r.get(dim) is not None]
        for c in ("none", "plain", "clock"):
            v = [r[dim] for r in dd if r["cond"] == c and r.get(dim) is not None]
            if c == "none":
                rows.append([dim, LABEL[c], len(v), f"{np.mean(v):.2f} ± {np.std(v):.2f}", "—", "—", "—"])
            else:
                cmp = compare(base, v)
                rows.append([dim, LABEL[c], len(v), f"{np.mean(v):.2f} ± {np.std(v):.2f}",
                             f"[{cmp['ci'][0]:+.2f}, {cmp['ci'][1]:+.2f}]", f"{cmp['cliffs']:+.2f}", f"{cmp['mw_p']:.3g}"])
    table("Push vs plain vs clock inside the DREAM loop (dream_def, Opus k=5)",
          ["dimension", "condition", "n", "mean ± sd", "DREAM − cond CI95", "Cliff's δ", "Mann-Whitney p"], rows)

# ---------------------------------------------------------------- instrument calibration
rj = load_json(RUNS / "dream_def" / "rejudge.json") or []
if rj:
    rows = []
    for jm in sorted({r["judge"] for r in rj}):
        sp = [r["spread"] for r in rj if r["judge"] == jm and r.get("spread") is not None]
        sd = [np.std([s for s in r["scores"] if s is not None]) for r in rj if r["judge"] == jm and r.get("median") is not None]
        zeros = [r for r in rj if r["judge"] == jm and r.get("median") == 0.0]
        rows.append([jm.split(".")[-1], len(sp), f"{np.mean(sp):.2f}", f"{np.mean(sd):.2f}", f"{len(zeros)}/{len(sp)}"])
    table("Instrument calibration — delta rubric, k=5 on the same 89 windows",
          ["judge", "windows", "mean intra-window spread", "mean within-sd", "windows scored exactly 0"], rows)
    fig, ax = plt.subplots(figsize=(4.4, 3))
    for jm, col in zip(sorted({r["judge"] for r in rj}), ("#2a78d6", "#eb6834")):
        sp = [r["spread"] for r in rj if r["judge"] == jm and r.get("spread") is not None]
        ax.hist(sp, bins=np.arange(0, 5.5, 0.5), alpha=0.55, color=col, label=jm.split(".")[-1], edgecolor="none")
    ax.set_xlabel("spread of 5 judgments of the same window (score points)"); ax.set_ylabel("windows")
    ax.legend(frameon=False, fontsize=8); ax.set_title("Judge resolution")
    fig.tight_layout(); fig.savefig(FIG / "fig5_judge_resolution.png", dpi=200); plt.close(fig)
    if sc:
        rows = []
        for dim in DIMS:
            sp = [r[dim + "_spread"] for r in sc if r.get(dim + "_spread") is not None]
            rows.append([dim, len(sp), f"{np.mean(sp):.2f}", f"{np.percentile(sp, 90):.2f}"])
        table("Instrument calibration — three-dimension rubric, Opus k=5", ["dimension", "windows", "mean spread", "p90 spread"], rows)

# ---------------------------------------------------------------- Phase 1: objective novelty
nov = load_json(RUNS / "exp1" / "novelty.json")
if nov:
    rows = []
    base4 = [r["novelty_by_n"]["4"] for r in nov.get("baseline", [])]
    for arm in ("baseline", "1", "2"):
        reps = nov.get(arm, [])
        if not reps:
            continue
        n4 = [r["novelty_by_n"]["4"] for r in reps]; n6 = [r["novelty_by_n"]["6"] for r in reps]
        cp = [r["longest_copied_len"] for r in reps]
        ci4 = "—" if arm == "baseline" else "[{:+.3f}, {:+.3f}]".format(*bootstrap_diff_ci(n4, base4))
        d4 = "—" if arm == "baseline" else f"{cliffs_delta(n4, base4):+.2f}"
        rows.append([{"baseline": "min-p baseline", "1": "λ=1", "2": "λ=2"}[arm], len(reps),
                     f"{100*np.mean(n4):.1f} ± {100*np.std(n4):.1f}", f"{100*np.mean(n6):.1f} ± {100*np.std(n6):.1f}",
                     ci4, d4, max(cp)])
    table("Phase 1 — objective novelty vs OLMo-2 training corpus (3 prompts × 5 seeds)",
          ["arm", "n", "novel 4-grams %", "novel 6-grams %", "Δ4 vs baseline CI95", "Cliff's δ", "max copied span (words)"], rows)
    fig, ax = plt.subplots(figsize=(4.4, 3))
    for i, (arm, col, lab) in enumerate((("baseline", "#4a3aa7", "min-p"), ("1", "#1baf7a", "λ=1"), ("2", "#2a78d6", "λ=2"))):
        v = [100 * r["novelty_by_n"]["4"] for r in nov.get(arm, [])]
        j = (np.random.default_rng(3).random(len(v)) - 0.5) * 0.3
        ax.scatter(np.full(len(v), i) + j, v, s=14, color=col, alpha=0.8, linewidths=0)
        ax.hlines(np.mean(v), i - 0.3, i + 0.3, color=col, lw=2)
    ax.set_xticks([0, 1, 2]); ax.set_xticklabels(["min-p", "λ=1", "λ=2"]); ax.set_ylabel("novel 4-grams (%)")
    ax.set_title("Phase 1: novelty vs training corpus"); fig.tight_layout()
    fig.savefig(FIG / "fig6_phase1_novelty.png", dpi=200); plt.close(fig)

# ---------------------------------------------------------------- Phase 2: improbable input
imp = load_json(RUNS / "improb2" / "cells.json") or []
if imp:
    judged = [c for c in imp if "judgment" in c]
    rows = []
    base = [c["judgment"]["delta_significance"] for c in judged if c["arm"] == "typical"]
    for arm in ("typical", "concepts", "improbable", "fragments", "register"):
        v = [c["judgment"]["delta_significance"] for c in judged if c["arm"] == arm]
        if not v:
            continue
        ci = "—" if arm == "typical" else "[{:+.2f}, {:+.2f}]".format(*bootstrap_diff_ci(v, base))
        rows.append([arm, len(v), f"{np.mean(v):.2f} ± {np.std(v):.2f}", ci,
                     "—" if arm == "typical" else f"{cliffs_delta(v, base):+.2f}"])
    table("Improbable-input definitive (stopped at 79/150; median of k=3 judges)",
          ["arm", "n", "delta significance", "Δ vs typical CI95", "Cliff's δ"], rows)
    x = [c["knn_distance"] for c in judged]; y = [c["judgment"]["delta_significance"] for c in judged]
    r_knn = np.corrcoef(x, y)[0, 1]
    xp = np.log([c["input_ppl"] for c in judged]); r_ppl = np.corrcoef(xp, y)[0, 1]
    md.append(f"\nCorrelation of judged delta with input improbability: kNN semantic distance r = {r_knn:+.3f}; log perplexity r = {r_ppl:+.3f} (n={len(y)}).\n")
    fig, ax = plt.subplots(figsize=(4.4, 3))
    cols = {"typical": "#4a3aa7", "concepts": "#eb6834", "improbable": "#2a78d6", "fragments": "#1baf7a", "register": "#eda100"}
    for arm, col in cols.items():
        pts = [(c["knn_distance"], c["judgment"]["delta_significance"]) for c in judged if c["arm"] == arm]
        if pts:
            xx, yy = zip(*pts)
            ax.scatter(xx, np.array(yy) + (np.random.default_rng(4).random(len(yy)) - 0.5) * 0.2, s=14, color=col, alpha=0.8, label=arm, linewidths=0)
    ax.set_xlabel("input distance from real prompts (kNN cosine)"); ax.set_ylabel("judged delta (median of 3)")
    ax.legend(fontsize=7, frameon=False); ax.set_title(f"Improbable input: r = {r_knn:+.2f}")
    fig.tight_layout(); fig.savefig(FIG / "fig7_improbable_input.png", dpi=200); plt.close(fig)

# ---------------------------------------------------------------- verified search
for tag, path in (("Qwen3-8B", RUNS / "evoverify_definitive" / "history.json"), ("Qwen3-30B-A3B", RUNS / "evoverify_30b" / "history.json")):
    h = load_json(path)
    if not h:
        continue
    rows = []
    for arm in ("plain", "antiprob"):
        hs = [v for v in h.values() if v["arm"] == arm]
        esc = [v["escape_gen"] for v in hs if v["escape_gen"] is not None]
        tests = [v["champion_test_excess"] for v in hs]
        rows.append([arm, len(hs), f"{len(esc)}/{len(hs)}", f"{np.mean(tests):.4f}", f"{np.min(tests):.4f}"])
    table(f"Verified search — {tag} (5 runs/arm, train 100, test 200; best-fit test excess ≈ 0.0603)",
          ["arm", "runs", "train-plateau escapes", "mean champion test excess", "best"], rows)

(ROOT / "docs" / "APPENDIX_ANALYSIS.md").write_text("\n".join(md) + "\n")
print("figures:", sorted(p.name for p in FIG.glob("*.png")))
print("appendix -> docs/APPENDIX_ANALYSIS.md")
