#!/usr/bin/env python3
"""Battery B-CONF analysis (pre-registered PLANO 2026-08-30 ~17h30; written
BEFORE the data). Primary: per-variant best gap to the classics (min over
valid candidates of train_excess - min(bf, ff)), pulse_kick - none, paired
over the 16 variants, exact sign-flip 2^16, one-sided (< 0). Declared
secondaries (BH): the same on TEST excess; pulse_ang - none; FAR subgroup
(descriptive CI); pooled find counts; valid production.
Writes docs/APPENDIX_BCONF.md."""

import itertools
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
R = ROOT / "runs/state_bconf"
ARMS = ("none", "pulse_kick", "pulse_ang")
VARIANTS = [("train", i) for i in range(10)] + [("far", i) for i in range(6)]


def load(arm):
    return json.loads((R / arm / "candidates.json").read_text())


def best_gap(cands, which, vi, field):
    vals = []
    for c in cands.values():
        if c.get("ok") and c["which"] == which and c["variant"] == vi and c.get(field) is not None:
            base = min(c[f"bf_{'train' if field == 'train' else 'test'}"],
                       c[f"ff_{'train' if field == 'train' else 'test'}"])
            vals.append(c[field] - base)
    return min(vals) if vals else None


def signflip(d, alt="less"):
    d = np.asarray(d, float)
    n = len(d)
    obs = d.mean()
    if alt == "less":
        cnt = sum(1 for sg in itertools.product((1, -1), repeat=n)
                  if (d * np.array(sg)).mean() <= obs + 1e-12)
    else:
        cnt = sum(1 for sg in itertools.product((1, -1), repeat=n)
                  if abs((d * np.array(sg)).mean()) >= abs(obs) - 1e-12)
    idx = np.random.default_rng(0).integers(0, n, (10000, n))
    lo, hi = np.percentile(d[idx].mean(1), [2.5, 97.5])
    return obs, float(lo), float(hi), cnt / 2 ** n


C = {arm: load(arm) for arm in ARMS}
L = ["# Appendix — Battery B-CONF: state stimulation and the verified tail "
     "(auto-generated by scripts/analysis_bconf.py)\n",
     "Pre-registered PLANO 2026-08-30 ~17h30 (analysis written before the "
     "data). 3 arms x 16 variants (10 train + 6 far) x 6 notebooks. Unit = "
     "variant; measure = best gap to min(best-fit, first-fit).\n"]


def paired_gaps(arm_a, arm_b, field):
    ds, dropped = [], []
    for which, vi in VARIANTS:
        a_ = best_gap(C[arm_a], which, vi, field)
        b_ = best_gap(C[arm_b], which, vi, field)
        if a_ is None or b_ is None:
            dropped.append(f"{which}_v{vi}")
            continue
        ds.append(a_ - b_)
    return np.asarray(ds), dropped


d, dropped = paired_gaps("pulse_kick", "none", "train")
obs, lo, hi, p = signflip(d, "less")
L.append("## Primary: pulse_kick − none, per-variant best train gap\n")
L.append("| Δ best gap [CI] | p (one-sided <0) | n pares | verdict |")
L.append("|---|---|---|---|")
L.append(f"| {obs:+.5f} [{lo:+.5f}, {hi:+.5f}] | {p:.4f} | {len(d)} | "
         f"{'SUPPORTED' if p < 0.05 and len(d) >= 12 else 'not supported'} |")
if dropped:
    L.append(f"\nDropped pairs (no valid candidate in an arm): {dropped}")

L.append("\n## Declared secondaries\n")
L.append("| test | Δ [CI] | p |")
L.append("|---|---|---|")
tests = [
    ("kick − none, TEST best gap (transfer, one-sided <0)", paired_gaps("pulse_kick", "none", "test")[0], "less"),
    ("ang − none, train best gap (two-sided)", paired_gaps("pulse_ang", "none", "train")[0], "two"),
]
for name, dd, alt in tests:
    if len(dd):
        o2, lo2, hi2, p2 = signflip(dd, alt)
        L.append(f"| {name} | {o2:+.5f} [{lo2:+.5f}, {hi2:+.5f}] | {p2:.4f} |")

far_d = []
for which, vi in VARIANTS:
    if which != "far":
        continue
    a_ = best_gap(C["pulse_kick"], which, vi, "train")
    b_ = best_gap(C["none"], which, vi, "train")
    if a_ is not None and b_ is not None:
        far_d.append(a_ - b_)
if far_d:
    fd = np.asarray(far_d)
    idx = np.random.default_rng(0).integers(0, len(fd), (10000, len(fd)))
    lo3, hi3 = np.percentile(fd[idx].mean(1), [2.5, 97.5])
    L.append(f"| FAR subgroup, kick − none (descriptive, n={len(fd)}) | "
             f"{fd.mean():+.5f} [{lo3:+.5f}, {hi3:+.5f}] | — |")

L.append("\n## Production and finds (pooled, descriptive)\n")
L.append("| arm | candidates | valid | distinct | finds | best train gap overall |")
L.append("|---|---|---|---|---|---|")
for arm in ARMS:
    ok = [c for c in C[arm].values() if c.get("ok") and c.get("train") is not None]
    finds = sum(1 for c in ok if c.get("find"))
    gaps = [c["train"] - min(c["bf_train"], c["ff_train"]) for c in ok]
    L.append(f"| {arm} | {len(C[arm])} | {len(ok)} | {len({c['hash'] for c in ok})} "
             f"| {finds} | {min(gaps):+.5f} |")

# ---- full ledger per arm (paper-4 review, M6): what the search produced ----
L.append("\n## Full ledger per arm (review M6)\n")
L.append("| arm | candidates | valid | valid rate | distinct programs | mean train gap | median train gap | best train gap | finds |")
L.append("|---|---|---|---|---|---|---|---|---|")
for arm in ARMS:
    allc = list(C[arm].values())
    ok = [c for c in allc if c.get("ok") and c.get("train") is not None]
    gaps = np.array([c["train"] - min(c["bf_train"], c["ff_train"]) for c in ok])
    L.append(f"| {arm} | {len(allc)} | {len(ok)} | {len(ok) / max(1, len(allc)):.2f} | {len({c['hash'] for c in ok})} "
             f"| {gaps.mean():+.5f} | {np.median(gaps):+.5f} | {gaps.min():+.5f} | {sum(1 for c in ok if c.get('find'))} |")

# ---- headroom split: variants where the carrier (none) had NOT reached the classics ----
L.append("\n## Headroom split (review M6): kick − none within variants where `none` still had room\n")
L.append("A variant has *headroom* when the none arm's best train gap is > 0 (the classics not yet matched); "
         "otherwise it sits at the floor and no arm can improve the measure.\n")
L.append("| subgroup | n variants | kick − none Δ [CI] | p (exact sign-flip, <0) | ang − none Δ [CI] |")
L.append("|---|---|---|---|---|")
for label, cond in (("headroom (none gap > 0)", lambda g: g > 1e-9), ("floor (none gap ≤ 0)", lambda g: g <= 1e-9)):
    dk, da = [], []
    for which, vi in VARIANTS:
        g0 = best_gap(C["none"], which, vi, "train")
        gk = best_gap(C["pulse_kick"], which, vi, "train")
        ga = best_gap(C["pulse_ang"], which, vi, "train")
        if g0 is None or not cond(g0):
            continue
        if gk is not None:
            dk.append(gk - g0)
        if ga is not None:
            da.append(ga - g0)
    if dk:
        o, lo4, hi4, p4 = signflip(np.asarray(dk), "less")
        sa = ""
        if da:
            oa, loa, hia, _ = signflip(np.asarray(da), "two")
            sa = f"{oa:+.5f} [{loa:+.5f}, {hia:+.5f}]"
        L.append(f"| {label} | {len(dk)} | {o:+.5f} [{lo4:+.5f}, {hi4:+.5f}] | {p4:.4f} | {sa} |")
    else:
        L.append(f"| {label} | 0 | — | — | — |")

out = ROOT / "docs/APPENDIX_BCONF.md"
out.write_text("\n".join(L) + "\n")
print("\n".join(L))
print(f"\nwrote {out}")
