#!/usr/bin/env python3
"""Battery PULSE analysis (pre-registered PLANO 2026-08-29 ~23h; written
BEFORE the data). Primary: judged surprise, pulse - habit, paired over the
10 premises, exact sign-flip 2^10 one-sided (> 0), coherence guard median
> -1.0. Declared secondaries: inter - habit (one-sided; does the paper-1
text interruption replicate here?), pulse - inter (two-sided), cheap C.
Writes docs/APPENDIX_PULSE.md."""

import itertools
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
R = ROOT / "runs/state_pulse"
PREMS = list(range(10))
ARMS = ("habit", "pulse", "inter")
DIMS = ("surprise", "connection", "coherence")

res = json.loads((R / "rejudge_gen.json").read_text())


def cellmean(prem, arm, dim):
    vals = [r[dim] for r in res if r["cell"] == f"p{prem}_{arm}" and r.get(dim) is not None]
    return float(np.mean(vals)) if vals else None


def paired(arm_a, arm_b, dim):
    ds = []
    for p in PREMS:
        x, y = cellmean(p, arm_a, dim), cellmean(p, arm_b, dim)
        if x is not None and y is not None:
            ds.append(x - y)
    return np.asarray(ds, float)


def signflip(d, alt="greater"):
    n = len(d)
    obs = d.mean()
    if alt == "greater":
        cnt = sum(1 for sg in itertools.product((1, -1), repeat=n)
                  if (d * np.array(sg)).mean() >= obs - 1e-12)
    else:
        cnt = sum(1 for sg in itertools.product((1, -1), repeat=n)
                  if abs((d * np.array(sg)).mean()) >= abs(obs) - 1e-12)
    idx = np.random.default_rng(0).integers(0, n, (10000, n))
    lo, hi = np.percentile(d[idx].mean(1), [2.5, 97.5])
    return obs, float(lo), float(hi), cnt / 2 ** n


L = ["# Appendix — Battery PULSE: state bursts on a habituated carrier "
     "(auto-generated by scripts/analysis_pulse.py)\n",
     "Pre-registered PLANO 2026-08-29 ~23h (analysis written before the data). "
     "Habituation in all arms; bursts of 32 every 300 at L18, alpha 1.0, "
     "rotating paper-1 kick directions; text interruption as positive anchor. "
     "P1 gen-protocol judging, k = 5. Unit = premise.\n"]

d_s = paired("pulse", "habit", "surprise")
d_c = paired("pulse", "habit", "coherence")
obs, lo, hi, p = signflip(d_s, "greater")
guard = float(np.median(d_c))
ok = p < 0.05 and guard > -1.0 and len(d_s) == 10
L.append("## Primary\n")
L.append("| contrast | Δ surprise [CI] | p (one-sided) | coherence guard | verdict |")
L.append("|---|---|---|---|---|")
L.append(f"| pulse − habit | {obs:+.3f} [{lo:+.3f}, {hi:+.3f}] | {p:.4f} | "
         f"{guard:+.2f} ({'ok' if guard > -1.0 else 'FAIL'}) | "
         f"{'SUPPORTED' if ok else 'not supported'} |")
if len(d_s) < 10:
    L.append(f"\nWARNING: only {len(d_s)} premises complete for the primary.")

L.append("\n## Declared secondaries\n")
L.append("| contrast | dim | Δ [CI] | p |")
L.append("|---|---|---|---|")
o2, lo2, hi2, p2 = signflip(paired("inter", "habit", "surprise"), "greater")
L.append(f"| inter − habit (anchor, one-sided) | surprise | {o2:+.3f} [{lo2:+.3f}, {hi2:+.3f}] | {p2:.4f} |")
for dim in DIMS:
    d3 = paired("pulse", "inter", dim)
    if len(d3):
        o3, lo3, hi3, p3 = signflip(d3, "two")
        L.append(f"| pulse − inter (two-sided) | {dim} | {o3:+.3f} [{lo3:+.3f}, {hi3:+.3f}] | {p3:.4f} |")

L.append("\n## Arm means (over premises)\n")
L.append("| arm | surprise | connection | coherence | clean NLL | distinct4 |")
L.append("|---|---|---|---|---|---|")
for arm in ARMS:
    row = [f"| {arm} "]
    for dim in DIMS:
        vs = [cellmean(p_, arm, dim) for p_ in PREMS]
        vs = [v for v in vs if v is not None]
        row.append(f"| {np.mean(vs):.2f} " if vs else "| — ")
    st = [json.loads((R / f"p{p_}_{arm}" / "state.json").read_text())
          for p_ in PREMS if (R / f"p{p_}_{arm}" / "state.json").exists()]
    row.append(f"| {np.mean([s['clean_nll_mean'] for s in st]):.2f} "
               f"| {np.mean([s['distinct4'] for s in st]):.3f} |")
    L.append("".join(row))

out = ROOT / "docs/APPENDIX_PULSE.md"
out.write_text("\n".join(L) + "\n")
print("\n".join(L))
print(f"\nwrote {out}")
