#!/usr/bin/env python3
"""Battery L analysis (pre-registered PLANO 2026-08-26): does behavioural repulsion recover
the tail that weight consolidation costs? Cells = problems (n = 6), exact paired sign-flip
(2^6 = 64), bootstrap 95% CI over problems. Writes docs/APPENDIX_L.md unless --smoke."""
import itertools, json, subprocess, sys
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
R = ROOT / "runs/frontier/L"
PROBS = ["circlepack26", "ringload15", "beatavg", "autocorr1", "sumdiff3", "maxmin16"]
ARMS = ["base", "baseD", "cons", "consD", "rand"]
SFT = {"cons": "sft_cons", "consD": "sft_cons", "rand": "sft_rand", "base": None, "baseD": None}

def tails(prob, arm):
    run = R / f"{prob}_{arm}"
    if not (run / "history.jsonl").exists(): return None
    sft = f"{R}/{SFT[arm]}_{prob}" if SFT[arm] else "none"
    cmd = [str(ROOT / ".venv/bin/python"), str(ROOT / "scripts/closed_loop.py"), "tails",
           "--problem", prob, "--pool", str(R / f"{prob}_pool"), "--run", str(run), "--sft", sft]
    p = subprocess.run(cmd, capture_output=True, text=True)
    if p.returncode != 0: return None
    return json.loads(p.stdout.strip().splitlines()[-1])

def signflip(d, alt):
    d = np.asarray(d, float); n = len(d); obs = d.mean()
    if alt == "greater":
        cnt = sum(1 for sg in itertools.product((1, -1), repeat=n) if (d * np.array(sg)).mean() >= obs - 1e-12)
    else:
        cnt = sum(1 for sg in itertools.product((1, -1), repeat=n) if abs((d * np.array(sg)).mean()) >= abs(obs) - 1e-12)
    idx = np.random.default_rng(0).integers(0, n, (10000, n)); bs = d[idx].mean(1)
    return obs, float(np.percentile(bs, 2.5)), float(np.percentile(bs, 97.5)), cnt / 2 ** n, n

smoke = "--smoke" in sys.argv
M = {}
for prob in PROBS:
    row = {arm: tails(prob, arm) for arm in ARMS}
    missing = [a for a, v in row.items() if v is None]
    if missing:
        print(f"[{'smoke' if smoke else 'WARN'}] {prob}: missing {missing}")
        if not smoke: continue
    M[prob] = row
ready = [p for p in PROBS if p in M and all(M[p][a] for a in ARMS)]
print(f"complete problems: {len(ready)} / {len(PROBS)}")
if not smoke and len(ready) < len(PROBS):
    sys.exit("battery incomplete — run with --smoke or wait for BATTERY-L DONE")
if not ready: sys.exit("nothing to analyse yet")

def col(arm, key): return np.array([M[p][arm][key] for p in ready], float)

md = ["# Appendix — Battery L: the closed loop (auto-generated by scripts/analysis_l.py)\n",
      "Session 1: bare search builds a candidate pool. Consolidation: LoRA on the pool's best 40 "
      "programs (cons) or on 40 random valid ones (rand). Session 2 (fresh seed): consolidation x "
      "behavioural repulsion, plus the random-adapter control. tail_p90 = share of valid, distinct, "
      "non-memorized session-2 candidates scoring above the session-1 pool's 90th percentile; "
      "tail_best = above the pool's best; echo = share of candidates reproducing a training "
      "signature. Cells = problems; exact paired sign-flip; bootstrap 95% CI over problems.\n",
      "## Pre-registered tests\n",
      "| test | contrast | measure | Δ [CI] | p | verdict |", "|---|---|---|---|---|---|"]

inter = (col("consD", "tail_p90") - col("cons", "tail_p90")) - (col("baseD", "tail_p90") - col("base", "tail_p90"))
tests = [("L1 (primary, one-sided >0)", "repulsion x consolidation", "tail_p90", inter, "greater"),
         ("L2 (two-sided)", "cons vs base", "tail_p90", col("cons", "tail_p90") - col("base", "tail_p90"), "two"),
         ("L3 (two-sided)", "cons vs base", "mean_frac", col("cons", "mean_frac") - col("base", "mean_frac"), "two"),
         ("L4a (two-sided)", "rand vs base", "tail_p90", col("rand", "tail_p90") - col("base", "tail_p90"), "two"),
         ("L4b (two-sided)", "rand vs base", "mean_frac", col("rand", "mean_frac") - col("base", "mean_frac"), "two")]
for name, contrast, key, d, alt in tests:
    r = signflip(d, alt)
    md.append(f"| {name} | {contrast} | {key} | {r[0]:+.4f} [{r[1]:+.4f}, {r[2]:+.4f}] | {r[3]:.4f} | "
              f"{'SUPPORTED' if r[3] <= 0.05 else 'not supported'} |")

md.append("\n## Descriptive (per arm, mean over problems)\n")
md.append("| arm | tail_p90 | tail_best | mean frac | best frac | div | echo | valid |")
md.append("|---|---|---|---|---|---|---|---|")
for arm in ARMS:
    md.append("| " + arm + " | " + " | ".join(f"{np.mean(col(arm, k)):.3f}" for k in
              ("tail_p90", "tail_best", "mean_frac", "best_frac", "div", "echo", "valid")) + " |")

md.append("\n## Per-problem tail_p90\n")
md.append("| problem | " + " | ".join(ARMS) + " | pool p90 | pool best |")
md.append("|---|" + "---|" * (len(ARMS) + 2))
for p in ready:
    md.append(f"| {p} | " + " | ".join(f"{M[p][a]['tail_p90']:.3f}" for a in ARMS) +
              f" | {M[p]['base']['pool_p90']:.3f} | {M[p]['base']['pool_best']:.3f} |")

out = "\n".join(md) + "\n"
print(out)
if not smoke:
    (ROOT / "docs/APPENDIX_L.md").write_text(out); print("wrote docs/APPENDIX_L.md")
