#!/usr/bin/env python3
"""Battery R4 analysis (response to the paper-4 review; pre-registered in
PLANO 2026-09-01 and WRITTEN BEFORE THE DATA). Single backend: torch bf16
Qwen3-8B-Base on a pod, cells in runs/r4/<pool><i>_<arm>, judged with the
P1 protocol (rejudge_gen.json). Unit = premise; paired tests.

R4b (30 premises: pools n/o/g): pulseG20 - inter in surprise — TOST with
the pre-registered margin +-0.75 (IC90 inside the band = equivalence; the
+-0.5 margin is REPORTED), two-sided sign-flip p, bootstrap CIs, a
fresh-only replication (self-copy filter) and pulseG20 - habit (> 0).
R4a (pool n, 10 premises, exact sign-flip 2^10, BH over the family):
(a) pulseG20 - sham_rand, - sham_shuf (> 0: does the CONTENT matter?);
(b) pulse_u10 - cont_a1, - cont_a0107 (> 0: the temporal law on ONE
carrier); (c) pulseG20 - reset_inter (two-sided). Descriptives: unguarded
dose ladder, effective displacement (cos / relative norm, M7), refusals,
cross-backend replication against the MLX parity cells.
Writes docs/APPENDIX_R4.md."""

import itertools
import json
import math
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
R = ROOT / "runs/r4"
MLX = ROOT / "runs/state_pulse"
DIMS = ("surprise", "connection", "coherence")
POOLS = {"n": "confirmatory", "o": "original", "g": "expository"}
PREMS = [f"{p}{i}" for p in "nog" for i in range(10)]
NPREM = [f"n{i}" for i in range(10)]
M_PRE, M_REP = 0.75, 0.5

res = json.loads((R / "rejudge_gen.json").read_text())
try:
    _sc = json.loads((ROOT / "runs/selfcopy_flags.json").read_text())
    SC = _sc.get("r4") or _sc.get(str(R)) or {}
except Exception:
    SC = {}


def cellmean(prem, arm, dim, fresh=False, src=res):
    vals = []
    for r in src:
        if r["cell"] != f"{prem}_{arm}" or r.get(dim) is None:
            continue
        if fresh and SC.get(r["cell"], {}).get(str(r["step"]), {}).get("frac", 0) >= 0.5:
            continue
        vals.append(r[dim])
    return float(np.mean(vals)) if vals else None


def paired(a, b, dim, prems=PREMS, fresh=False):
    ds = []
    for p in prems:
        x, y = cellmean(p, a, dim, fresh), cellmean(p, b, dim, fresh)
        if x is not None and y is not None:
            ds.append(x - y)
    return np.asarray(ds, float)


def signflip(d, alt="greater", exact_max=14):
    n = len(d)
    if n == 0:
        return float("nan"), float("nan"), float("nan"), float("nan")
    obs = d.mean()
    stat = (lambda m: m >= obs - 1e-12) if alt == "greater" else (lambda m: abs(m) >= abs(obs) - 1e-12)
    if n <= exact_max:
        cnt = sum(1 for sg in itertools.product((1, -1), repeat=n) if stat((d * np.array(sg)).mean()))
        p = cnt / 2 ** n
    else:  # Monte-Carlo sign-flip, 200k draws, seeded
        sg = np.random.default_rng(1).choice((1, -1), size=(200000, n))
        p = (np.sum([stat(m) for m in (d * sg).mean(1)]) + 1) / (200000 + 1)
    idx = np.random.default_rng(0).integers(0, n, (20000, n))
    lo, hi = np.percentile(d[idx].mean(1), [2.5, 97.5])
    return float(obs), float(lo), float(hi), float(p)


def tost(d, margin):
    """Two one-sided t tests; equivalence when both p < .05 (== IC90 in band)."""
    from scipy import stats
    n = len(d)
    m, sd = d.mean(), d.std(ddof=1)
    se = sd / math.sqrt(n)
    t_lo = (m + margin) / se          # H0: mean <= -margin
    t_hi = (m - margin) / se          # H0: mean >= +margin
    p_lo = 1 - stats.t.cdf(t_lo, n - 1)
    p_hi = stats.t.cdf(t_hi, n - 1)
    tcrit = stats.t.ppf(0.95, n - 1)
    ic90 = (m - tcrit * se, m + tcrit * se)
    return {"mean": m, "sd": sd, "n": n, "ic90": ic90, "p_tost": max(p_lo, p_hi),
            "equiv": max(p_lo, p_hi) < 0.05}


def power_tost(sd, n, margin):
    """Power to declare equivalence when the true difference is 0."""
    from scipy import stats
    se = sd / math.sqrt(n)
    half = stats.t.ppf(0.95, n - 1) * se
    if half >= margin:
        return 0.0
    return float(stats.norm.cdf((margin - half) / se) - stats.norm.cdf(-(margin - half) / se))


def tci_top(d, conf=0.95):
    from scipy import stats
    n = len(d); m = d.mean(); se = d.std(ddof=1) / math.sqrt(max(1, n))
    tc = stats.t.ppf(0.5 + conf / 2, n - 1) if n > 1 else float("nan")
    return m, m - tc * se, m + tc * se


def bh(ps):
    ps = np.asarray(ps, float)
    order = np.argsort(ps)
    q = np.empty(len(ps))
    prev = 1.0
    for rank, i in list(enumerate(order))[::-1]:
        prev = min(prev, ps[i] * len(ps) / (rank + 1))
        q[i] = prev
    return q


def armmean(arm, dim, prems, fresh=False):
    v = [cellmean(p, arm, dim, fresh) for p in prems]
    v = [x for x in v if x is not None]
    return (float(np.mean(v)), len(v)) if v else (float("nan"), 0)


def state_field(prem, arm, key):
    f = R / f"{prem}_{arm}" / "state.json"
    if not f.exists():
        return None
    return json.loads(f.read_text()).get(key)


L = ["# Appendix — Battery R4: the review's controls (auto-generated by scripts/analysis_r4.py)\n",
     "Pre-registered in PLANO (2026-09-01) before any cell; analysis written before the data. "
     "One backend for every cell (torch bf16, Qwen3-8B-Base, layer 18, 1500 tokens, RNG 0, "
     "habituated carrier); judge protocol P1 (generated-only 96-token windows, k = 5, median). "
     "Unit = premise.\n"]

# ---------------- R4b: parity extension with TOST ----------------
L.append("## R4b — pulseG20 versus text interruption on 30 premises (TOST)\n")
d = paired("pulseG20", "inter", "surprise")
obs, lo, hi, p2 = signflip(d, "two")
L.append(f"Premises complete: {len(d)} of 30 "
         f"(pools: " + ", ".join(f"{POOLS[k]} {len(paired('pulseG20', 'inter', 'surprise', [f'{k}{i}' for i in range(10)]))}" for k in "nog") + ").\n")
if len(d) >= 3:
    t75, t50 = tost(d, M_PRE), tost(d, M_REP)
    L.append("| contrast | Δ surprise [CI95] | p two-sided | IC90 | TOST ±0.75 (pre-registered) | TOST ±0.5 (reported) |")
    L.append("|---|---|---|---|---|---|")
    L.append(f"| pulseG20 − inter | {obs:+.3f} [{lo:+.3f}, {hi:+.3f}] | {p2:.4f} | "
             f"[{t75['ic90'][0]:+.3f}, {t75['ic90'][1]:+.3f}] | p = {t75['p_tost']:.4f} → "
             f"**{'EQUIVALENT' if t75['equiv'] else 'not shown'}** | p = {t50['p_tost']:.4f} → "
             f"{'equivalent' if t50['equiv'] else 'not shown'} |")
    L.append(f"\nPaired SD {t75['sd']:.3f}; power to declare ±0.75-equivalence at a true difference of 0 "
             f"with this SD and n = {len(d)}: {power_tost(t75['sd'], len(d), M_PRE):.2f} "
             f"(±0.5: {power_tost(t75['sd'], len(d), M_REP):.2f}).")
    for dim in ("connection", "coherence"):
        dd = paired("pulseG20", "inter", dim)
        o2, l2, h2, pp = signflip(dd, "two")
        L.append(f"- {dim}: Δ {o2:+.3f} [{l2:+.3f}, {h2:+.3f}], p = {pp:.4f}")
    df = paired("pulseG20", "inter", "surprise", fresh=True)
    if SC and len(df):
        o3, l3, h3, p3 = signflip(df, "two")
        t75f = tost(df, M_PRE)
        L.append(f"- fresh-only replication (self-copied windows removed): Δ {o3:+.3f} [{l3:+.3f}, {h3:+.3f}], "
                 f"p = {p3:.4f}, TOST ±0.75 p = {t75f['p_tost']:.4f}")
    dh = paired("pulseG20", "habit", "surprise")
    o4, l4, h4, p4 = signflip(dh, "greater")
    L.append(f"- replication pulseG20 − habit (one-sided > 0): Δ {o4:+.3f} [{l4:+.3f}, {h4:+.3f}], p = {p4:.4f}")
    di = paired("inter", "habit", "surprise")
    o5, l5, h5, p5 = signflip(di, "greater")
    L.append(f"- inter − habit (one-sided > 0): Δ {o5:+.3f} [{l5:+.3f}, {h5:+.3f}], p = {p5:.4f}")

L.append("\n### Arm means by premise pool (surprise / connection / coherence)\n")
L.append("| pool | habit | pulseG20 | inter |")
L.append("|---|---|---|---|")
for k in "nog":
    prems = [f"{k}{i}" for i in range(10)]
    row = f"| {POOLS[k]} |"
    for arm in ("habit", "pulseG20", "inter"):
        vals = [armmean(arm, dim, prems)[0] for dim in DIMS]
        row += " " + " / ".join(f"{v:.2f}" for v in vals) + f" (n={armmean(arm, 'surprise', prems)[1]}) |"
    L.append(row)

# cross-backend replication against the MLX parity cells (same 10 premises)
if (MLX / "rejudge_gen.json").exists():
    mres = json.loads((MLX / "rejudge_gen.json").read_text())
    L.append("\n### Cross-backend replication (confirmatory pool): MLX 8-bit (paper's parity battery) vs torch bf16 (R4)\n")
    L.append("| arm | MLX surprise | torch surprise | MLX connection | torch connection | MLX coherence | torch coherence |")
    L.append("|---|---|---|---|---|---|---|")
    for arm in ("habit", "pulseG20", "inter"):
        row = f"| {arm} |"
        for dim in DIMS:
            mv = [cellmean(f"p{i}", arm, dim, src=mres) for i in range(10)]
            tv = [cellmean(f"n{i}", arm, dim) for i in range(10)]
            mv = [x for x in mv if x is not None]; tv = [x for x in tv if x is not None]
            row += f" {np.mean(mv):.2f} | {np.mean(tv) if tv else float('nan'):.2f} |"
        L.append(row)
    dm = np.array([cellmean(f"p{i}", "pulseG20", "surprise", src=mres) - cellmean(f"p{i}", "inter", "surprise", src=mres)
                   for i in range(10) if cellmean(f"p{i}", "pulseG20", "surprise", src=mres) is not None
                   and cellmean(f"p{i}", "inter", "surprise", src=mres) is not None])
    dt = paired("pulseG20", "inter", "surprise", NPREM)
    L.append(f"\npulseG20 − inter on the same 10 premises: MLX {dm.mean():+.3f}, torch {dt.mean():+.3f} (n = {len(dt)}).")

# ---------------- R4a: the review's controls ----------------
L.append("\n## R4a — shams, one-carrier temporal law, reset comparator (confirmatory pool, n = 10)\n")
family = [
    ("(a1) pulseG20 − sham_rand (surprise, > 0)", "pulseG20", "sham_rand", "surprise", "greater"),
    ("(a2) pulseG20 − sham_shuf (surprise, > 0)", "pulseG20", "sham_shuf", "surprise", "greater"),
    ("(b1) pulse_u10 − cont_a1 (surprise, > 0)", "pulse_u10", "cont_a1", "surprise", "greater"),
    ("(b2) pulse_u10 − cont_a0107 (surprise, > 0)", "pulse_u10", "cont_a0107", "surprise", "greater"),
    ("(c) pulseG20 − reset_inter (surprise, two-sided)", "pulseG20", "reset_inter", "surprise", "two"),
]
rows, ps = [], []
for name, a, b, dim, alt in family:
    dd = paired(a, b, dim, NPREM)
    if len(dd):
        o, l2, h2, pp = signflip(dd, alt)
        g = paired(a, b, "coherence", NPREM)
        rows.append((name, o, l2, h2, pp, len(dd), float(np.median(g)) if len(g) else float("nan")))
        ps.append(pp)
qs = bh(ps) if ps else []
L.append("| contrast | Δ [CI95] | p | q (BH, family of 5) | n | coherence guard (median Δ) |")
L.append("|---|---|---|---|---|---|")
for (name, o, l2, h2, pp, n, g), q in zip(rows, qs):
    L.append(f"| {name} | {o:+.3f} [{l2:+.3f}, {h2:+.3f}] | {pp:.4f} | {q:.4f} | {n} | {g:+.2f} ({'ok' if g > -1.0 else 'FAIL'}) |")

L.append("\n### Every R4a arm against the carrier (habit), two-sided, descriptive\n")
L.append("| arm | surprise (mean) | Δ vs habit [CI95] | p | connection | coherence | clean NLL | distinct-4 |")
L.append("|---|---|---|---|---|---|---|---|")
for arm in ("habit", "inter", "reset_inter", "pulseG20", "sham_rand", "sham_shuf", "pulse_u10", "pulse_u15", "pulse_u20", "cont_a1", "cont_a0107"):
    s, n = armmean(arm, "surprise", NPREM)
    if n == 0:
        continue
    dd = paired(arm, "habit", "surprise", NPREM)
    o, l2, h2, pp = signflip(dd, "two") if arm != "habit" and len(dd) else (0.0, 0.0, 0.0, 1.0)
    nll = [state_field(p, arm, "clean_nll_mean") for p in NPREM]; nll = [x for x in nll if x is not None]
    d4 = [state_field(p, arm, "distinct4") for p in NPREM]; d4 = [x for x in d4 if x is not None]
    L.append(f"| {arm} | {s:.2f} (n={n}) | {o:+.3f} [{l2:+.3f}, {h2:+.3f}] | {pp:.4f} | "
             f"{armmean(arm, 'connection', NPREM)[0]:.2f} | {armmean(arm, 'coherence', NPREM)[0]:.2f} | "
             f"{np.mean(nll) if nll else float('nan'):.3f} | {np.mean(d4) if d4 else float('nan'):.3f} |")

# ---------------- R5 (round 2): one-carrier temporal contrast on 30 premises ----------------
def tci(d, conf=0.95):
    from scipy import stats
    n = len(d); m = d.mean(); se = d.std(ddof=1) / math.sqrt(max(1, n))
    tc = stats.t.ppf(0.5 + conf / 2, n - 1) if n > 1 else float("nan")
    return m, m - tc * se, m + tc * se

d5 = paired("pulse_u10", "cont_a1", "surprise")
if len(d5) > 10:
    L.append("\n## R5 (round 2, pre-registered): pulse versus continuous on one carrier, 30 premises\n")
    L.append("| contrast | Δ surprise | CI95 (t) | p (one-sided > 0, MC sign-flip) | n | coherence guard (median Δ) |")
    L.append("|---|---|---|---|---|---|")
    for name, a_, b_, alt in (("(1) pulse_u10 − cont_a1", "pulse_u10", "cont_a1", "greater"),
                              ("(2) pulse_u10 − cont_a0107", "pulse_u10", "cont_a0107", "greater"),
                              ("cont_a1 − habit", "cont_a1", "habit", "two"),
                              ("cont_a0107 − habit", "cont_a0107", "habit", "two"),
                              ("pulse_u10 − habit", "pulse_u10", "habit", "greater")):
        dd = paired(a_, b_, "surprise")
        if not len(dd):
            continue
        o, _, _, pp = signflip(dd, alt)
        m, lo_, hi_ = tci(dd)
        g = paired(a_, b_, "coherence")
        L.append(f"| {name} | {o:+.3f} | [{lo_:+.3f}, {hi_:+.3f}] | {pp:.4f} | {len(dd)} | {float(np.median(g)):+.2f} ({'ok' if np.median(g) > -1.0 else 'FAIL'}) |")

# ---------------- round 3 (N2): matched-layout re-judging ----------------
MF = R / "rejudge_matched.json"
if MF.exists() and json.loads(MF.read_text()):
    mres = json.loads(MF.read_text())

    def cm2(src, cell, dim, since_set=None, step_pred=None):
        v = [r[dim] for r in src if r["cell"] == cell and r.get(dim) is not None
             and (since_set is None or r.get("since") in since_set)
             and (step_pred is None or step_pred(r["step"]))]
        return float(np.mean(v)) if v else None

    L.append("\n## Matched-layout re-judging (round 3, N2): pulseG20 and habit judged at +32/+160 after each burst end\n")
    L.append("Text interruption keeps its already-judged +32/+160 windows; the state arm and the carrier are re-judged at the same offsets after the end of each burst (pseudo-injections at 300k, length 32). Unit = premise, 30 premises.\n")
    for dim in DIMS:
        d = np.array([cm2(mres, f"{p}_pulseG20", dim, {32, 160}) - cm2(res, f"{p}_inter", dim, {32, 160})
                      for p in PREMS if cm2(mres, f"{p}_pulseG20", dim, {32, 160}) is not None and cm2(res, f"{p}_inter", dim, {32, 160}) is not None])
        if not len(d):
            continue
        o, _, _, pp = signflip(d, "two"); m, tlo, thi = tci_top(d)
        line = f"- pulseG20 − inter, {dim}: Δ {o:+.3f}, 95% t-CI [{tlo:+.3f}, {thi:+.3f}], two-sided p = {pp:.4f}, n = {len(d)}"
        if dim == "surprise":
            t75, t50 = tost(d, M_PRE), tost(d, M_REP)
            line += f"; TOST ±0.75 p = {t75['p_tost']:.4f} ({'EQUIVALENT' if t75['equiv'] else 'not shown'}), ±0.5 p = {t50['p_tost']:.4f} ({'equivalent' if t50['equiv'] else 'not shown'})"
        L.append(line)
    for dim in DIMS:
        d = np.array([cm2(mres, f"{p}_pulseG20", dim, {32, 160}) - cm2(mres, f"{p}_habit", dim, {32, 160})
                      for p in PREMS if cm2(mres, f"{p}_pulseG20", dim, {32, 160}) is not None and cm2(mres, f"{p}_habit", dim, {32, 160}) is not None])
        if len(d):
            o, _, _, pp = signflip(d, "greater" if dim == "surprise" else "two"); m, tlo, thi = tci_top(d)
            L.append(f"- pulseG20 − habit (matched), {dim}: Δ {o:+.3f}, 95% t-CI [{tlo:+.3f}, {thi:+.3f}], p = {pp:.4f}")

    def offmean(arm, src, dim, **kw):
        v = [cm2(src, f"{p}_{arm}", dim, **kw) for p in PREMS]; v = [x for x in v if x is not None]
        return f"{np.mean(v):.2f}" if v else "—"
    for dim in DIMS:
        L.append(f"\n### {dim} by offset from the intervention end (mean over premises)\n")
        L.append("| arm | +0 (burst end, grid) | +32 | +160 | +182 (grid) |")
        L.append("|---|---|---|---|---|")
        L.append(f"| inter | — | {offmean('inter', res, dim, since_set={32})} | {offmean('inter', res, dim, since_set={160})} | — |")
        for arm in ("pulseG20", "habit"):
            L.append(f"| {arm} | {offmean(arm, res, dim, step_pred=lambda s: s >= 300 and (s - 32) % 300 == 0)} | {offmean(arm, mres, dim, since_set={32})} | {offmean(arm, mres, dim, since_set={160})} | {offmean(arm, res, dim, step_pred=lambda s: (s - 32) % 300 != 0)} |")

# ---------------- M7: effective displacement ----------------
L.append("\n## Effective displacement after guards (M7) — mean over fired tokens, per arm\n")
L.append("| arm | α | guards | fired/cell | cos(h_pre, h_post) | ‖Δh‖/‖h‖ |")
L.append("|---|---|---|---|---|---|")
for arm in ("pulse_u10", "pulse_u15", "pulse_u20", "pulseG20", "sham_rand", "sham_shuf", "cont_a1", "cont_a0107"):
    cs = [state_field(p, arm, "disp_cos_mean") for p in NPREM]; cs = [x for x in cs if x is not None]
    rs = [state_field(p, arm, "disp_rel_mean") for p in NPREM]; rs = [x for x in rs if x is not None]
    if not cs:
        continue
    s0 = json.loads((R / f"n0_{arm}" / "state.json").read_text()) if (R / f"n0_{arm}" / "state.json").exists() else {}
    guards = "+".join(k for k in ("anchor", "keep_norm") if s0.get(k)) or "none"
    L.append(f"| {arm} | {s0.get('alpha')} | {guards} | {s0.get('fired')} | {np.mean(cs):.4f} ± {np.std(cs):.4f} | {np.mean(rs):.4f} ± {np.std(rs):.4f} |")

# ---------------- judge refusals / coverage ----------------
L.append("\n## Judge coverage per arm (windows judged; a window is dropped only when every k call refused)\n")
conds = sorted({r["cond"] for r in res})
L.append("| arm | windows | mean k | premises |")
L.append("|---|---|---|---|")
for c in conds:
    rs = [r for r in res if r["cond"] == c]
    L.append(f"| {c} | {len(rs)} | {np.mean([r['k'] for r in rs]):.2f} | {len({r['cell'] for r in rs})} |")

manip = R / "manip.json"
if manip.exists():
    m = json.loads(manip.read_text())
    L.append("\n## Manipulation check (judge names the injected subject; chance = 25%)\n")
    L.append("| arm | windows | hit rate | 'none of these' |")
    L.append("|---|---|---|---|")
    for c, v in sorted(m.items()):
        hit = f"{v['hit']:.2f}" if v.get("hit") is not None else "— (no subject)"
        L.append(f"| {c} | {v['n']} | {hit} | {v['none']:.2f} |")

out = ROOT / "docs/APPENDIX_R4.md"
out.write_text("\n".join(L) + "\n")
print("\n".join(L))
print(f"\nwritten {out}")
