#!/usr/bin/env python3
"""Battery H1-minimal analysis (pre-registered in PLANO; written BEFORE the
data). Primary: judged surprise, pulseG20 - inter (the prompt-matched rival),
paired over 10 premises, sign-flip 2^10 one-sided (> 0), coherence guard
median > -1.0. Verdict tiers: SUPERA (p < .05 + guard); PARIDADE (two-sided
p >= .05 and |mean| < 0.5, descriptive); INFERIOR otherwise. Declared
secondary family (BH q reported): rotor - inter, repelA - habit,
pulseG15 - inter (existing data), and H4: repelA - repelN in coherence,
one-sided (> 0) — the anchor law's registered prediction.
Writes docs/APPENDIX_H1.md."""

import itertools
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
R = ROOT / "runs/state_pulse"
PREMS = list(range(10))
ARMS = ("habit", "inter", "pulse", "pulseG", "pulseG15", "pulseG20", "rotor", "repelA", "repelN")
DIMS = ("surprise", "connection", "coherence")

res = json.loads((R / "rejudge_gen.json").read_text())


def cellmean(prem, arm, dim):
    vals = [r[dim] for r in res if r["cell"] == f"p{prem}_{arm}" and r.get(dim) is not None]
    return float(np.mean(vals)) if vals else None


def paired(arm_a, arm_b, dim):
    ds = []
    for p in PREMS:
        x, y = cellmean(p, arm_a, dim), cellmean(p, arm_b, dim)
        if x is not None and y is not None:
            ds.append(x - y)
    return np.asarray(ds, float)


def signflip(d, alt="greater"):
    n = len(d)
    obs = d.mean()
    if alt == "greater":
        cnt = sum(1 for sg in itertools.product((1, -1), repeat=n)
                  if (d * np.array(sg)).mean() >= obs - 1e-12)
    else:
        cnt = sum(1 for sg in itertools.product((1, -1), repeat=n)
                  if abs((d * np.array(sg)).mean()) >= abs(obs) - 1e-12)
    idx = np.random.default_rng(0).integers(0, n, (10000, n))
    lo, hi = np.percentile(d[idx].mean(1), [2.5, 97.5])
    return obs, float(lo), float(hi), cnt / 2 ** n


def bh(ps):
    order = np.argsort(ps)
    q = np.empty(len(ps))
    prev = 1.0
    for rank, i in list(enumerate(order))[::-1]:
        prev = min(prev, ps[i] * len(ps) / (rank + 1))
        q[i] = prev
    return q


L = ["# Appendix — Battery H1-minimal: state versus the prompt with the same "
     "information (auto-generated by scripts/analysis_h1.py)\n",
     "Pre-registered in PLANO before launch (analysis written before the data). "
     "New arms pulseG20 / rotor / repelA / repelN on the habituated carrier; "
     "controls and ladder context are the PULSO-1/2 arms (same premises, RNG, "
     "protocol, judge). Unit = premise.\n"]

# ---- primary ----
d_s = paired("pulseG20", "inter", "surprise")
d_c = paired("pulseG20", "inter", "coherence")
obs, lo, hi, p1 = signflip(d_s, "greater")
_, _, _, p2 = signflip(d_s, "two")
guard = float(np.median(d_c))
if p1 < 0.05 and guard > -1.0:
    verdict = "SUPERA"
elif p2 >= 0.05 and abs(obs) < 0.5:
    verdict = "PARIDADE (descritiva)"
else:
    verdict = "INFERIOR"
L.append("## Primary: pulseG20 − inter (prompt-matched rival)\n")
L.append("| Δ surprise [CI] | p (one-sided >0) | p (two-sided) | coherence guard | verdict |")
L.append("|---|---|---|---|---|")
L.append(f"| {obs:+.3f} [{lo:+.3f}, {hi:+.3f}] | {p1:.4f} | {p2:.4f} | "
         f"{guard:+.2f} ({'ok' if guard > -1.0 else 'FAIL'}) | **{verdict}** |")
if len(d_s) < 10:
    L.append(f"\nWARNING: only {len(d_s)} premises complete for the primary.")

# ---- declared secondary family with BH ----
tests = [
    ("rotor − inter (surprise, two-sided)", paired("rotor", "inter", "surprise"), "two"),
    ("repelA − habit (surprise, two-sided)", paired("repelA", "habit", "surprise"), "two"),
    ("pulseG15 − inter (surprise, two-sided)", paired("pulseG15", "inter", "surprise"), "two"),
    ("H4: repelA − repelN (coherence, one-sided >0)", paired("repelA", "repelN", "coherence"), "greater"),
]
rows, ps = [], []
for name, d, alt in tests:
    if len(d):
        o, lo2, hi2, pp = signflip(d, alt)
        rows.append((name, o, lo2, hi2, pp))
        ps.append(pp)
qs = bh(np.array(ps)) if ps else []
L.append("\n## Declared secondaries (BH q over the family)\n")
L.append("| test | Δ [CI] | p | q (BH) |")
L.append("|---|---|---|---|")
for (name, o, lo2, hi2, pp), q in zip(rows, qs):
    L.append(f"| {name} | {o:+.3f} [{lo2:+.3f}, {hi2:+.3f}] | {pp:.4f} | {q:.4f} |")

L.append("\n## Arm means (over premises)\n")
L.append("| arm | surprise | connection | coherence | clean NLL | distinct4 |")
L.append("|---|---|---|---|---|---|")
for arm in ARMS:
    row = [f"| {arm} "]
    for dim in DIMS:
        vs = [cellmean(p_, arm, dim) for p_ in PREMS]
        vs = [v for v in vs if v is not None]
        row.append(f"| {np.mean(vs):.2f} " if vs else "| — ")
    st = [json.loads((R / f"p{p_}_{arm}" / "state.json").read_text())
          for p_ in PREMS if (R / f"p{p_}_{arm}" / "state.json").exists()]
    if st:
        row.append(f"| {np.mean([s['clean_nll_mean'] for s in st]):.2f} "
                   f"| {np.mean([s['distinct4'] for s in st]):.3f} |")
    else:
        row.append("| — | — |")
    L.append("".join(row))

out = ROOT / "docs/APPENDIX_H1.md"
out.write_text("\n".join(L) + "\n")
print("\n".join(L))
print(f"\nwrote {out}")
