#!/usr/bin/env python3
"""Battery GEN analysis (pre-registered PLANO 2026-08-31; written before any
judged window exists). Per model: primary pulse - habit in judged surprise
(paired over the 10 premises, sign-flip 2^10 one-sided > 0, coherence guard
median > -1.0 — does the positive replicate?); declared secondary
pulse - inter (parity tiers as in H1: SUPERA / PARIDADE |mean|<0.5 two-sided
n.s. / INFERIOR). Reads runs/pod/gen_<tag>/rejudge_gen.json.
Writes docs/APPENDIX_GEN5.md (the phase-5 generality ladder).

    python scripts/analysis_gen_ladder.py olmo qwen14 qwen38 [oss]
"""

import itertools
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
PREMS = list(range(10))
DIMS = ("surprise", "connection", "coherence")


def signflip(d, alt="greater"):
    n = len(d)
    obs = d.mean()
    if alt == "greater":
        cnt = sum(1 for sg in itertools.product((1, -1), repeat=n)
                  if (d * np.array(sg)).mean() >= obs - 1e-12)
    else:
        cnt = sum(1 for sg in itertools.product((1, -1), repeat=n)
                  if abs((d * np.array(sg)).mean()) >= abs(obs) - 1e-12)
    idx = np.random.default_rng(0).integers(0, n, (10000, n))
    lo, hi = np.percentile(d[idx].mean(1), [2.5, 97.5])
    return obs, float(lo), float(hi), cnt / 2 ** n


def model_block(tag: str):
    R = ROOT / f"runs/pod/gen_{tag}"
    res = json.loads((R / "rejudge_gen.json").read_text())

    def cellmean(prem, arm, dim):
        vals = [r[dim] for r in res if r["cell"] == f"p{prem}_{arm}" and r.get(dim) is not None]
        return float(np.mean(vals)) if vals else None

    def paired(a_, b_, dim):
        ds = []
        for p_ in PREMS:
            x, y = cellmean(p_, a_, dim), cellmean(p_, b_, dim)
            if x is not None and y is not None:
                ds.append(x - y)
        return np.asarray(ds, float)

    L = [f"\n## {tag}\n"]
    d_s, d_c = paired("pulse", "habit", "surprise"), paired("pulse", "habit", "coherence")
    obs, lo, hi, p = signflip(d_s, "greater")
    guard = float(np.median(d_c))
    ok = p < 0.05 and guard > -1.0 and len(d_s) == 10
    L.append("| contrast | Δ [CI] | p | guard | verdict |")
    L.append("|---|---|---|---|---|")
    L.append(f"| pulse − habit (primária, surprise, >0) | {obs:+.3f} [{lo:+.3f}, {hi:+.3f}] | "
             f"{p:.4f} | {guard:+.2f} | {'REPLICA' if ok else 'não replica'} |")
    d2 = paired("pulse", "inter", "surprise")
    if len(d2):
        o2, lo2, hi2, p1 = signflip(d2, "greater")
        _, _, _, p2 = signflip(d2, "two")
        if p1 < 0.05:
            tier = "SUPERA"
        elif p2 >= 0.05 and abs(o2) < 0.5:
            tier = "PARIDADE"
        else:
            tier = "INFERIOR"
        L.append(f"| pulse − inter (secundária, surprise) | {o2:+.3f} [{lo2:+.3f}, {hi2:+.3f}] | "
                 f"1s {p1:.4f} / 2s {p2:.4f} | — | {tier} |")
    L.append("\n| arm | surprise | connection | coherence | clean NLL | distinct4 |")
    L.append("|---|---|---|---|---|---|")
    for arm in ("habit", "pulse", "inter"):
        row = [f"| {arm} "]
        for dim in DIMS:
            vs = [cellmean(p_, arm, dim) for p_ in PREMS]
            vs = [v for v in vs if v is not None]
            row.append(f"| {np.mean(vs):.2f} " if vs else "| — ")
        st = [json.loads((R / f"p{p_}_{arm}" / "state.json").read_text())
              for p_ in PREMS if (R / f"p{p_}_{arm}" / "state.json").exists()]
        if st:
            row.append(f"| {np.mean([s['clean_nll_mean'] for s in st]):.2f} "
                       f"| {np.mean([s['distinct4'] for s in st]):.3f} |")
        else:
            row.append("| — | — |")
        L.append("".join(row))
    return L


tags = sys.argv[1:] or ["olmo", "qwen14", "qwen38"]
out_lines = ["# Appendix — Battery GEN: the generality ladder of the state pulse "
             "(auto-generated by scripts/analysis_gen_ladder.py)\n",
             "Pre-registered PLANO 2026-08-31. Per model: does pulse − habit "
             "replicate, and where does pulse − inter land (SUPERA / PARIDADE / "
             "INFERIOR)? 10 confirmatory premises, P1 gen protocol, k = 5, "
             "layer at 50% depth, dose alpha 2.0 in state-scale units.\n"]
for tag in tags:
    try:
        out_lines += model_block(tag)
    except FileNotFoundError:
        out_lines.append(f"\n## {tag}\n(sem rejudge_gen.json — pendente)\n")
out = ROOT / "docs/APPENDIX_GEN5.md"
out.write_text("\n".join(out_lines) + "\n")
print("\n".join(out_lines))
print(f"\nwrote {out}")
