#!/usr/bin/env python3
"""Full 2^3 factorial analysis (pre-registered 2026-08-24 ~08:40, PLANO): effect-coded +-1
analysis of frac over the cube M(memory=B) x A(agenda=C) x R(repulsion=D); cell = problem
(n = 9), replicates pooled by mean; exact paired sign-flip permutation (2^9).
Confirmatory: I1 (primary, one-sided) M x R > 0; I2 A x R (two-sided); I3 mains M, A, R
(two-sided, BH over the three). Everything else descriptive. Writes docs/APPENDIX_F23.md
unless --smoke (print only, allows incomplete cube)."""
import itertools, json, sys
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
R = ROOT / "runs/frontier/F"
sys.path.insert(0, str(ROOT / "scripts")); sys.path.insert(0, str(ROOT / "src"))
from frontier_search import PROBLEMS

ARMS = ["A", "B", "C", "D", "BC", "BD", "CD", "E"]
# the nine pre-registered factorial problems (beatavg20k is a record-run variant, outside the design)
FPROBS = ["circlepack26", "autocorr1", "beatavg", "ringload15", "isofree64",
          "sumdiff3", "maxmin16", "heiltri11", "factn180"]
# effect codes (M, A, R) per arm; E = all three on
CODE = {"A": (-1, -1, -1), "B": (1, -1, -1), "C": (-1, 1, -1), "D": (-1, -1, 1),
        "BC": (1, 1, -1), "BD": (1, -1, 1), "CD": (-1, 1, 1), "E": (1, 1, 1)}
TERMS = [("M", lambda m, a, r: m), ("A", lambda m, a, r: a), ("R", lambda m, a, r: r),
         ("MxA", lambda m, a, r: m * a), ("MxR", lambda m, a, r: m * r),
         ("AxR", lambda m, a, r: a * r), ("MxAxR", lambda m, a, r: m * a * r)]

def seed_score(P):
    from creative_machine.frontier_exec import run_candidate
    return run_candidate(P["seed_program"], P["module"], P["entry"], P["args"])["score"]

def metrics_file(f, prob, budget=120):
    P = PROBLEMS[prob]
    rows = [json.loads(l) for l in f.read_text().splitlines() if l.strip()][:budget]
    if not rows: return None
    s0 = SEED[prob]; rec = P["best_known"]; sgn = 1 if P["maximize"] else -1
    best = s0
    for r in rows:
        if r.get("ok") and (sgn * (r["score"] - best) > 0): best = r["score"]
    ok = [r for r in rows if r.get("ok")]
    return {"frac": (sgn * (best - s0)) / max(1e-12, sgn * (rec - s0)),
            "div": (len({r.get("sig") for r in ok}) / len(ok)) if ok else 0.0}

def pooled(prob, arm):
    ms = []
    for d in (f"{prob}_{arm}", f"{prob}_{arm}_s1"):
        f = R / d / "history.jsonl"
        if f.exists():
            m = metrics_file(f, prob)
            if m: ms.append(m)
    if not ms: return None
    return {k: float(np.mean([m[k] for m in ms])) for k in ("frac", "div")} | {"reps": len(ms)}

def signflip(d, alt):
    d = np.asarray(d, float); n = len(d); obs = d.mean()
    if alt == "greater":
        cnt = sum(1 for sg in itertools.product((1, -1), repeat=n) if (d * np.array(sg)).mean() >= obs - 1e-12)
    else:
        cnt = sum(1 for sg in itertools.product((1, -1), repeat=n) if abs((d * np.array(sg)).mean()) >= abs(obs) - 1e-12)
    idx = np.random.default_rng(0).integers(0, n, (10000, n)); bs = d[idx].mean(1)
    return obs, float(np.percentile(bs, 2.5)), float(np.percentile(bs, 97.5)), cnt / 2 ** n, n

def bh(ps):
    m = len(ps); order = np.argsort(ps); q = np.empty(m)
    prev = 1.0
    for rank, i in list(enumerate(order))[::-1]:
        prev = min(prev, ps[i] * m / (rank + 1)); q[i] = prev
    return q

smoke = "--smoke" in sys.argv
SEED = {p: seed_score(P) for p, P in PROBLEMS.items()}

cells = {}   # cells[prob][arm] = pooled metrics
complete = True
for prob in FPROBS:
    row = {arm: pooled(prob, arm) for arm in ARMS}
    missing = [a for a, m in row.items() if m is None]
    incomplete = [a for a, m in row.items() if m and m["reps"] < 2]
    if missing or incomplete:
        complete = False
        print(f"[{'smoke' if smoke else 'WARN'}] {prob}: missing={missing} single-rep={incomplete}")
        if missing: continue
    cells[prob] = row

probs = sorted(cells)
print(f"problems in cube: {len(probs)} / {len(FPROBS)}")
if not smoke and (len(probs) < len(FPROBS) or not complete):
    sys.exit("cube incomplete (need all 9 problems x 8 arms x 2 reps) — run with --smoke or wait for F-23 DONE")

# per-problem effect contrasts (coefficient scale: (1/8) sum x_t * y)
eff = {t: [] for t, _ in TERMS}
for prob in probs:
    for t, fn in TERMS:
        eff[t].append(sum(fn(*CODE[arm]) * cells[prob][arm]["frac"] for arm in ARMS) / 8.0)

res = {}
res["MxR"] = signflip(eff["MxR"], "greater")            # I1 primary, one-sided
res["AxR"] = signflip(eff["AxR"], "two")                # I2
mains = {t: signflip(eff[t], "two") for t in ("M", "A", "R")}  # I3
qs = bh([mains[t][3] for t in ("M", "A", "R")])
desc = {t: signflip(eff[t], "two") for t in ("MxA", "MxAxR")}  # descriptive only

md = ["# Appendix — the completed 2^3 factorial (auto-generated by scripts/analysis_23.py)\n",
      "Factors: M = schematic notebook memory (arm letter B), A = agenda (C), R = behavioural "
      "repulsion (D). Cube cells = the 8 arms A/B/C/D/BC/BD/CD/E over 9 problems x 2 replicates "
      "(frac pooled by replicate mean). Effects on the coefficient scale beta_t = (1/8) sum x_t y "
      "(half the classical effect). Cell = problem (n = 9); exact paired sign-flip (2^9 = 512); "
      "bootstrap 95% CI over problems.\n",
      "## Pre-registered tests (PLANO 2026-08-24 ~08:40)\n",
      "| test | term | beta [CI] | p | q (BH) | verdict |", "|---|---|---|---|---|---|"]

def rowfmt(name, term, r, p_reported, q=None, alpha=0.05):
    verdict = "SUPPORTED" if p_reported <= alpha else "not supported"
    return (f"| {name} | {term} | {r[0]:+.4f} [{r[1]:+.4f}, {r[2]:+.4f}] | {r[3]:.4f} | "
            f"{'' if q is None else f'{q:.4f}'} | {verdict} |")

md.append(rowfmt("I1 (primary, one-sided >0)", "M x R", res["MxR"], res["MxR"][3]))
md.append(rowfmt("I2 (two-sided)", "A x R", res["AxR"], res["AxR"][3]))
for i, t in enumerate(("M", "A", "R")):
    md.append(rowfmt(f"I3 main (two-sided, BH)", t, mains[t], qs[i], qs[i]))
md.append("\nDescriptive (not confirmatory per pre-registration):\n")
md.append("| term | beta [CI] | p (two-sided) |"); md.append("|---|---|---|")
for t in ("MxA", "MxAxR"):
    r = desc[t]; md.append(f"| {t} | {r[0]:+.4f} [{r[1]:+.4f}, {r[2]:+.4f}] | {r[3]:.4f} |")

md.append("\n## Cube cell means (frac; mean over problems, replicates pooled)\n")
md.append("| arm | M | A | R | frac | div |"); md.append("|---|---|---|---|---|---|")
for arm in ARMS:
    m, a, r = CODE[arm]
    fr = np.mean([cells[p][arm]["frac"] for p in probs]); dv = np.mean([cells[p][arm]["div"] for p in probs])
    md.append(f"| {arm} | {'+' if m>0 else '-'} | {'+' if a>0 else '-'} | {'+' if r>0 else '-'} | {fr:.3f} | {dv:.3f} |")

md.append("\n## Per-problem M x R interaction contrasts (frac)\n")
md.append("| problem | beta_MxR |"); md.append("|---|---|")
for prob, v in zip(probs, eff["MxR"]):
    md.append(f"| {prob} | {v:+.4f} |")

out = "\n".join(md) + "\n"
print(out)
if not smoke:
    (ROOT / "docs/APPENDIX_F23.md").write_text(out)
    print("wrote docs/APPENDIX_F23.md")
