#!/usr/bin/env python3
"""Battery H2 analysis (pre-registered PLANO 2026-08-29; written BEFORE the data).

Primary: judged surprise of the band core (L18 x alpha {0.25, 0.5, 0.75}) vs
bare, unit = premise (n = 10), exact paired sign-flip 2^10, one-sided (> 0),
alpha = 0.05; coherence guard: median paired coherence difference > -1.0.
H2 supported iff both. Declared secondaries: (a) core vs prompt-matched
(H1 preview, exploratory label); (b) dose curves at L18; (c) layer
comparison; (d) cheap C (clean NLL, distinct4). Writes docs/APPENDIX_H2.md."""

import itertools
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
R = ROOT / "runs/state_h2"
PREMS = list(range(10))
CORE = [f"L18_a{a}" for a in ("0.25", "0.5", "0.75")]
DIMS = ("surprise", "connection", "coherence")

res = json.loads((R / "rejudge_gen.json").read_text())


def cellmean(prem: int, arm: str, dim: str):
    vals = [r[dim] for r in res if r["cell"] == f"p{prem}_{arm}" and r.get(dim) is not None]
    return float(np.mean(vals)) if vals else None


def armmean(prem: int, arms, dim: str):
    vs = [cellmean(prem, a, dim) for a in arms]
    vs = [v for v in vs if v is not None]
    return float(np.mean(vs)) if vs else None


def paired(arms_a, arm_b, dim: str):
    ds, kept = [], []
    for p in PREMS:
        x = armmean(p, arms_a, dim) if isinstance(arms_a, list) else cellmean(p, arms_a, dim)
        y = cellmean(p, arm_b, dim)
        if x is None or y is None:
            continue
        ds.append(x - y)
        kept.append(p)
    return np.asarray(ds, float), kept


def signflip(d, alt="greater"):
    n = len(d)
    obs = d.mean()
    if alt == "greater":
        cnt = sum(1 for sg in itertools.product((1, -1), repeat=n)
                  if (d * np.array(sg)).mean() >= obs - 1e-12)
    else:
        cnt = sum(1 for sg in itertools.product((1, -1), repeat=n)
                  if abs((d * np.array(sg)).mean()) >= abs(obs) - 1e-12)
    idx = np.random.default_rng(0).integers(0, n, (10000, n))
    lo, hi = np.percentile(d[idx].mean(1), [2.5, 97.5])
    return obs, float(lo), float(hi), cnt / 2 ** n


def cheap(prem: int, arm: str):
    p = R / f"p{prem}_{arm}" / "state.json"
    return json.loads(p.read_text()) if p.exists() else None


L = []
L.append("# Appendix — Battery H2: the fertile band of state translation "
         "(auto-generated by scripts/analysis_h2.py)\n")
L.append("Pre-registered PLANO 2026-08-29 (analysis written before the data). "
         "10 confirmatory premises, fixed concept, P1 gen-protocol judging "
         "(96-token generated-only windows, k = 5 medians). Unit = premise.\n")

# ---- primary ----
d_s, kept = paired(CORE, "bare", "surprise")
d_c, _ = paired(CORE, "bare", "coherence")
obs, lo, hi, p = signflip(d_s, "greater")
guard = float(np.median(d_c))
supported = (p < 0.05) and (guard > -1.0) and len(d_s) == 10
L.append("## Primary (H2)\n")
L.append("| contrast | measure | Δ [CI] | p (one-sided) | coherence guard (median Δ) | verdict |")
L.append("|---|---|---|---|---|---|")
L.append(f"| band core (L18, α .25/.5/.75) − bare | judged surprise | "
         f"{obs:+.3f} [{lo:+.3f}, {hi:+.3f}] | {p:.4f} | {guard:+.2f} "
         f"(> −1.0: {'yes' if guard > -1.0 else 'NO'}) | "
         f"{'SUPPORTED' if supported else 'not supported'} |")
if len(kept) < 10:
    L.append(f"\nWARNING: only {len(kept)} premises complete: {kept}")

# ---- secondary a: vs prompt-matched ----
L.append("\n## Secondary (declared): core vs prompt-matched (H1 preview, exploratory)\n")
L.append("| contrast | dim | Δ [CI] | p (two-sided) |")
L.append("|---|---|---|---|")
for dim in DIMS:
    d, _ = paired(CORE, "prompt", dim)
    if len(d):
        o, lo2, hi2, p2 = signflip(d, "two")
        L.append(f"| core − prompt | {dim} | {o:+.3f} [{lo2:+.3f}, {hi2:+.3f}] | {p2:.4f} |")

# ---- secondary b: dose curves at L18 ----
L.append("\n## Dose curves at L18 (mean over premises; bootstrap 95% CI)\n")
L.append("| α | surprise | connection | coherence | clean NLL | distinct4 |")
L.append("|---|---|---|---|---|---|")
for a in ("0.1", "0.25", "0.5", "0.75", "1", "1.5"):
    arm = f"L18_a{a}"
    row = [f"| {a} "]
    for dim in DIMS:
        vs = [cellmean(p_, arm, dim) for p_ in PREMS]
        vs = np.asarray([v for v in vs if v is not None], float)
        if len(vs):
            idx = np.random.default_rng(0).integers(0, len(vs), (10000, len(vs)))
            lo3, hi3 = np.percentile(vs[idx].mean(1), [2.5, 97.5])
            row.append(f"| {vs.mean():.2f} [{lo3:.2f},{hi3:.2f}] ")
        else:
            row.append("| — ")
    st = [cheap(p_, arm) for p_ in PREMS]
    st = [s for s in st if s]
    row.append(f"| {np.mean([s['clean_nll_mean'] for s in st]):.2f} "
               f"| {np.mean([s['distinct4'] for s in st]):.3f} |")
    L.append("".join(row))

# baseline rows
for arm in ("bare", "prompt"):
    st = [cheap(p_, arm) for p_ in PREMS]
    st = [s for s in st if s]
    vals = {dim: [cellmean(p_, arm, dim) for p_ in PREMS] for dim in DIMS}
    row = [f"| {arm} "]
    for dim in DIMS:
        vs = np.asarray([v for v in vals[dim] if v is not None], float)
        row.append(f"| {vs.mean():.2f} " if len(vs) else "| — ")
    row.append(f"| {np.mean([s['clean_nll_mean'] for s in st]):.2f} "
               f"| {np.mean([s['distinct4'] for s in st]):.3f} |")
    L.append("".join(row))

# ---- secondary c: layers at core doses ----
L.append("\n## Layers at core doses (surprise / coherence, mean over premises)\n")
L.append("| layer | α 0.25 | α 0.5 | α 0.75 |")
L.append("|---|---|---|---|")
for layer in (14, 18, 22):
    row = [f"| L{layer} "]
    for a in ("0.25", "0.5", "0.75"):
        s_ = [cellmean(p_, f"L{layer}_a{a}", "surprise") for p_ in PREMS]
        c_ = [cellmean(p_, f"L{layer}_a{a}", "coherence") for p_ in PREMS]
        s_ = [v for v in s_ if v is not None]
        c_ = [v for v in c_ if v is not None]
        row.append(f"| {np.mean(s_):.2f} / {np.mean(c_):.2f} " if s_ else "| — ")
    L.append("".join(row) + "|")

out = ROOT / "docs/APPENDIX_H2.md"
out.write_text("\n".join(L) + "\n")
print("\n".join(L[:20]))
print(f"\nwrote {out}")
