#!/usr/bin/env python3
"""Battery 2 analysis — what is the interruption made of? Reads the offline
judgments of runs/dream_b2 (new conditions) and runs/dream_scaffold (bare,
bare_reseed, scaffold0, abl_salience) and answers four questions with
tables (docs/APPENDIX_B2.md) and figures (docs/figures/fig8_*.png):

  Q1 confound   bare vs bare+habituation vs bare+clock reseed
  Q2 content    neutral seed vs re-encounter vs premise vs own past (clock 150)
  Q3 timing     salience-timed re-encounter vs clock re-encounter vs salience-only
  Q4 frequency  clock 75 / 150 / 300 / 600 (neutral seed)

Unit = judged window (median of k=5 Opus judgments); per-seed means give the
paired view (all conditions share the same 10 seeds).

    python scripts/analysis_b2.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))
from creative_machine.stats import bootstrap_diff_ci  # noqa: E402

import matplotlib  # noqa: E402
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from scipy import stats as sps  # noqa: E402

plt.rcParams.update({"font.size": 9, "axes.spines.top": False, "axes.spines.right": False,
                     "axes.grid": True, "grid.alpha": 0.25, "grid.linewidth": 0.5})


def cliffs_delta(a, b) -> float:
    a, b = np.asarray(a), np.asarray(b)
    gt = sum((x > b).sum() for x in a)
    lt = sum((x < b).sum() for x in a)
    return float((gt - lt) / (len(a) * len(b)))

RUNS, FIG, DOCS = ROOT / "runs", ROOT / "docs" / "figures", ROOT / "docs"
DIMS = ("surprise", "connection", "coherence")
PAL = {"bare": "#4a3aa7", "bare_habit": "#7a7a7a", "bare_reseed": "#eda100", "scaffold0": "#2a78d6", "abl_salience": "#1baf7a",
       "clock_reenc": "#2a78d6", "clock_premise": "#eb6834", "clock_self": "#1baf7a", "sal_reenc": "#c2185b",
       "clock75": "#9ecae1", "clock300": "#4292c6", "clock600": "#08306b", "clock900": "#041c3d", "clock900_reenc": "#7b1fa2"}
LABEL = {"bare": "bare", "bare_habit": "bare +\nhabituation", "bare_reseed": "bare +\nclock reseed", "scaffold0": "DREAM\nscaffold",
         "abl_salience": "salience\nonly", "clock_reenc": "clock:\nre-encounter", "clock_premise": "clock:\npremise",
         "clock_self": "clock:\nown past", "sal_reenc": "salience:\nre-encounter", "clock75": "clock 75", "clock300": "clock 300",
         "clock600": "clock 600", "clock900": "clock 900", "clock900_reenc": "clock 900:\nre-encounter"}


def load(run: str):
    p = RUNS / run / "rejudge_surprise.json"
    rows = json.loads(p.read_text()) if p.exists() else []
    cache = {}
    for r in rows:
        r["run"] = run
        r["seed"] = r["cell"].split("_", 1)[0]
        # phase of the judged window: tokens since the last injection before its end (exact for cells with 'pos')
        if r["cell"] not in cache:
            rj = json.loads((RUNS / run / r["cell"] / "run.json").read_text())
            inj_pos = sorted(x[2]["pos"] for x in rj.get("reseeds", []) if len(x) > 2 and isinstance(x[2], dict) and "pos" in x[2])
            ev_pos = {(e["step"], e["kind"]): e.get("pos") for e in rj["events"]}
            cache[r["cell"]] = (inj_pos, ev_pos)
        inj_pos, ev_pos = cache[r["cell"]]
        pos = ev_pos.get((r["step"], r["kind"]))
        if not inj_pos:  # older cells: no positions recorded — use generated steps for both (drift cancels)
            rj_steps = sorted(x[0] for x in json.loads((RUNS / run / r["cell"] / "run.json").read_text()).get("reseeds", []))
            inj_pos, pos = rj_steps, r["step"]
        r["since_injection"] = r["segment_len"] = None
        if pos is not None and inj_pos:
            before = [p_ for p_ in inj_pos if p_ < pos]
            after = [p_ for p_ in inj_pos if p_ >= pos]
            if before:
                r["since_injection"] = pos - before[-1]
                r["segment_len"] = (after[0] - before[-1]) if after else None
    return rows


ALL = load("dream_scaffold") + load("dream_b2")
FAM8B = load("dream_fam8b")
md = ["# Appendix — battery 2 (auto-generated by scripts/analysis_b2.py)\n"]


MIN_STEP = 100  # windows ending before 100 generated tokens are degenerate (the first clock cut at step 2 is two tokens)


def sel(cond: str, kinds=None, pool=None):
    pool = ALL if pool is None else pool
    return [r for r in pool if r["cond"] == cond and (kinds is None or r["kind"] in kinds) and r.get("surprise") is not None
            and r["step"] >= MIN_STEP]


def desc(rows, dim):
    v = np.array([r[dim] for r in rows], dtype=float)
    return f"{v.mean():.2f} ± {v.std():.2f}" if len(v) else "—"


def paired_seed_ci(rows_a, rows_b, dim):
    """Paired bootstrap over seeds of the per-seed mean difference."""
    sa = {}; sb = {}
    for r in rows_a: sa.setdefault(r["seed"], []).append(r[dim])
    for r in rows_b: sb.setdefault(r["seed"], []).append(r[dim])
    seeds = sorted(set(sa) & set(sb))
    if len(seeds) < 3:
        return None
    d = np.array([np.mean(sa[s]) - np.mean(sb[s]) for s in seeds])
    rng = np.random.default_rng(0)
    bs = [rng.choice(d, len(d)).mean() for _ in range(10000)]
    return float(d.mean()), float(np.percentile(bs, 2.5)), float(np.percentile(bs, 97.5)), len(seeds)


def compare_table(title, spec, ref, pool=None):
    """spec: list of (cond, kinds, label). ref: index into spec of the reference row."""
    md.append(f"\n### {title}\n")
    md.append("| condition | windows | kind | surprise | connection | coherence | good (S≥5&H≥5) |")
    md.append("|---|---|---|---|---|---|---|")
    data = []
    for cond, kinds, label in spec:
        rows = sel(cond, kinds, pool)
        data.append(rows)
        good = sum(1 for r in rows if r["surprise"] >= 5 and r["coherence"] >= 5)
        md.append(f"| {label} | {len(rows)} | {'/'.join(sorted({r['kind'] for r in rows})) or '—'} | " +
                  " | ".join(desc(rows, d) for d in DIMS) + f" | {good}/{len(rows)} |")
    ref_rows = data[ref]
    md.append(f"\nvs **{spec[ref][2]}** (Δ mean, 95% bootstrap CI over windows; Cliff's δ; Mann-Whitney p; paired-by-seed Δ [CI]):\n")
    md.append("| condition | dim | Δ [CI] | δ | p | paired-by-seed Δ [CI] (n seeds) |")
    md.append("|---|---|---|---|---|---|")
    for (cond, kinds, label), rows in zip(spec, data):
        if rows is ref_rows or not rows or not ref_rows:
            continue
        for d in DIMS:
            a = [r[d] for r in rows]; b = [r[d] for r in ref_rows]
            lo, hi = bootstrap_diff_ci(a, b)
            p = sps.mannwhitneyu(a, b, alternative="two-sided").pvalue
            ps = paired_seed_ci(rows, ref_rows, d)
            pstr = f"{ps[0]:+.2f} [{ps[1]:+.2f}, {ps[2]:+.2f}] ({ps[3]})" if ps else "—"
            star = "**" if (lo > 0 or hi < 0) else ""
            md.append(f"| {label} | {d} | {star}{np.mean(a)-np.mean(b):+.2f} [{lo:+.2f}, {hi:+.2f}]{star} | {cliffs_delta(a, b):+.2f} | {p:.1e} | {pstr} |")
    return data


def violin_fig(fname, spec, title, pool=None):
    conds = [(c, k, l) for c, k, l in spec if sel(c, k, pool)]
    fig, axes = plt.subplots(1, 3, figsize=(3.4 * 3 + 1, 3.6), sharey=True)
    for ax, dim in zip(axes, DIMS):
        vals = [[r[dim] for r in sel(c, k, pool)] for c, k, l in conds]
        parts = ax.violinplot(vals, positions=range(len(conds)), showmeans=False, showextrema=False, widths=0.85)
        for body, (c, k, l) in zip(parts["bodies"], conds):
            body.set_facecolor(PAL.get(c, "#888")); body.set_alpha(0.35); body.set_edgecolor("none")
        for i, ((c, k, l), v) in enumerate(zip(conds, vals)):
            m = np.mean(v); lo, hi = np.percentile([np.mean(np.random.default_rng(j).choice(v, len(v))) for j in range(400)], [2.5, 97.5])
            ax.plot([i - 0.28, i + 0.28], [m, m], color=PAL.get(c, "#888"), lw=2.2)
            ax.plot([i, i], [lo, hi], color=PAL.get(c, "#888"), lw=1)
            ax.text(i, -0.55, f"n={len(v)}", ha="center", fontsize=7, color="#555")
        ax.set_xticks(range(len(conds))); ax.set_xticklabels([LABEL.get(c, c) for c, k, l in conds], fontsize=7.5)
        ax.set_title(dim, fontsize=10); ax.set_ylim(-0.9, 10.5); ax.axhline(5, color="#bbb", lw=0.7, ls=":")
    axes[0].set_ylabel("judged score (0–10), median of k=5")
    fig.suptitle(title, fontsize=10, y=1.02)
    fig.tight_layout(); fig.savefig(FIG / fname, dpi=170, bbox_inches="tight"); plt.close(fig)
    print("figure ->", FIG / fname)


def main() -> None:
    n_b2 = sum(1 for r in ALL if r["run"] == "dream_b2")
    md.append(f"{len(ALL)} judged windows total ({n_b2} from battery 2).\n")

    # Q1 confound
    q1 = [("bare", None, "bare (no habituation, no interruption)"),
          ("bare_habit", None, "bare + habituation (no interruption)"),
          ("bare_reseed", ("clock",), "bare + habituation + clock reseed 150"),
          ("scaffold0", None, "DREAM scaffold (λ=0)")]
    compare_table("Q1 — the confound: habituation without interruption", q1, ref=1)
    violin_fig("fig8_q1_habituation.png", q1, "Q1 — is it habituation or interruption? bare vs bare+habituation vs bare+habituation+clock reseed")

    # Q2 content
    q2 = [("bare_reseed", ("clock",), "neutral subject change (clock 150)"),
          ("clock_reenc", ("cut",), "re-encounter stitch (clock 150)"),
          ("clock_premise", ("cut",), "the premise itself (clock 150)"),
          ("clock_self", ("cut",), "the stream's own past (clock 150)")]
    compare_table("Q2 — content of the interruption (windows right before each injection)", q2, ref=0)
    violin_fig("fig8_q2_content.png", q2, "Q2 — what the interruption injects: neutral change vs re-encounter vs premise vs own past (clock 150)")

    # Q3 timing (sal_reenc event windows may be labeled by the salience kind or as 'cut', depending on the run's version)
    EVENT = ("cut", "jump", "crystallize", "recurrence")
    q3 = [("clock_reenc", ("cut",), "re-encounter on the clock (150)"),
          ("clock900_reenc", ("cut",), "re-encounter on the clock (900; matched frequency)"),
          ("clock900", ("cut",), "neutral change on the clock (900; matched frequency)"),
          ("sal_reenc", EVENT, "re-encounter on salience events (event windows)"),
          ("sal_reenc", ("clock",), "re-encounter on salience events (uniform windows)"),
          ("clock900_reenc", ("clock",), "re-encounter on the clock (900), uniform windows"),
          ("clock900", ("clock",), "neutral change on the clock (900), uniform windows"),
          ("abl_salience", None, "salience only, no injection (event windows)")]
    compare_table("Q3 — timing of the re-encounter: clock vs salience", q3, ref=0)
    violin_fig("fig8_q3_timing.png", q3, "Q3 — when to return: clock vs salience-timed re-encounter")

    # Q4 frequency
    q4 = [("clock75", ("cut",), "every 75 (before injection)"),
          ("bare_reseed", ("clock",), "every 150 (before injection)"),
          ("clock300", ("cut",), "every 300 (before injection)"),
          ("clock600", ("cut",), "every 600 (before injection)"),
          ("clock900", ("cut",), "every 900 (before injection)"),
          ("clock300", ("clock",), "every 300 (mid-segment)"),
          ("clock600", ("clock",), "every 600 (mid-segment)"),
          ("clock900", ("clock",), "every 900 (mid-segment)")]
    compare_table("Q4 — frequency of interruption (neutral seed)", q4, ref=1)
    violin_fig("fig8_q4_frequency.png", q4[:5], "Q4 — how often to interrupt: neutral subject change every 75 / 150 / 300 / 600 / 900 tokens")

    # Q4b — phase: judged score vs tokens since the last injection, per frequency (all judged windows of the cell)
    freq = [("clock75", 75), ("bare_reseed", 150), ("clock300", 300), ("clock600", 600), ("clock900", 900)]
    md.append("\n### Q4b — phase within the segment: score by tokens since the last interruption (all judged windows, both kinds)\n")
    md.append("| every | windows | pooled surprise | conn | coh | early (≤160 tokens since injection) S / C / H | late (>160) S / C / H |")
    md.append("|---|---|---|---|---|---|---|")
    fig, axes = plt.subplots(1, 2, figsize=(12, 3.8))
    for cond, every in freq:
        rows = [r for r in sel(cond) if r.get("since_injection") is not None]
        if not rows:
            continue
        early = [r for r in rows if r["since_injection"] <= 160]
        late = [r for r in rows if r["since_injection"] > 160]
        f = lambda rs, d: f"{np.mean([r[d] for r in rs]):.2f}" if rs else "—"
        md.append(f"| {every} | {len(rows)} | {f(rows,'surprise')} | {f(rows,'connection')} | {f(rows,'coherence')} | "
                  f"{f(early,'surprise')} / {f(early,'connection')} / {f(early,'coherence')} (n={len(early)}) | "
                  f"{f(late,'surprise')} / {f(late,'connection')} / {f(late,'coherence')} (n={len(late)}) |")
        # binned curve
        bins = [(0, 160), (160, 320), (320, 480), (480, 640), (640, 1000)]
        xs, ys, es = [], [], []
        for lo, hi in bins:
            b = [r["surprise"] for r in rows if lo < r["since_injection"] <= hi]
            if len(b) >= 3:
                xs.append((lo + hi) / 2); ys.append(np.mean(b)); es.append(np.std(b) / np.sqrt(len(b)))
        if xs:
            axes[0].errorbar(xs, ys, yerr=es, fmt="-o", ms=4, capsize=2, color=PAL.get(cond, "#666"), label=f"every {every} (n={len(rows)})")
        pooled = [r["surprise"] for r in rows]
        axes[1].errorbar([every], [np.mean(pooled)], yerr=[np.std(pooled) / np.sqrt(len(pooled))], fmt="o", ms=6, capsize=3, color=PAL.get(cond, "#666"))
        for d, mk in (("connection", "s"), ("coherence", "^")):
            v = [r[d] for r in rows]
            axes[1].errorbar([every], [np.mean(v)], yerr=[np.std(v) / np.sqrt(len(v))], fmt=mk, ms=5, capsize=2, color=PAL.get(cond, "#666"), alpha=0.6)
    axes[0].set_xlabel("tokens since the last interruption (window end)"); axes[0].set_ylabel("judged surprise (mean ± s.e.)")
    axes[0].set_title("surprise decays with distance from the interruption", fontsize=9); axes[0].legend(fontsize=7, frameon=False); axes[0].grid(alpha=0.25)
    axes[1].set_xscale("log"); axes[1].set_xticks([75, 150, 300, 600, 900]); axes[1].set_xticklabels(["75", "150", "300", "600", "900"])
    axes[1].set_xlabel("interruption period (tokens)"); axes[1].set_ylabel("mean over all judged windows"); axes[1].grid(alpha=0.25)
    axes[1].set_title("● surprise  ■ connection  ▲ coherence, by period (all windows pooled)", fontsize=9)
    fig.suptitle("Q4b — how often to interrupt: phase and period", fontsize=10)
    fig.tight_layout(); fig.savefig(FIG / "fig8_q4b_phase.png", dpi=170, bbox_inches="tight"); plt.close(fig)
    print("figure ->", FIG / "fig8_q4b_phase.png")

    # Q5 — second generator family (Qwen3-8B-Base): the ladder replicates?
    if FAM8B:
        EV = ("jump", "crystallize", "recurrence", "cut", "clock")
        q5 = [("bare", None, "8B: bare"),
              ("bare_habit", None, "8B: bare + habituation"),
              ("bare_reseed", ("cut", "clock"), "8B: bare + habituation + clock reseed 150"),
              ("scaffold0", EV, "8B: DREAM scaffold (λ=0)")]
        compare_table("Q5 — second generator family (Qwen3-8B-Base, 10 seeds)", q5, ref=1, pool=FAM8B)
        violin_fig("fig8_q5_family8b.png", q5, "Q5 — the ladder on a second generator family (Qwen3-8B-Base): bare → habituation → interruption → scaffold", pool=FAM8B)

    out = DOCS / "APPENDIX_B2.md"
    out.write_text("\n".join(md) + "\n")
    print("\n".join(md))
    print("->", out)


if __name__ == "__main__":
    main()
