#!/usr/bin/env python3
"""Battery PULSE-2 analysis (pre-registered PLANO 2026-08-30 morning; written
BEFORE the data). Primary: judged coherence, pulseG - pulse, paired over the
10 premises, sign-flip 2^10 one-sided (> 0) — do the guards heal the fabric?
Primary's guard: median paired surprise pulseG - pulse > -0.5. Declared
secondaries: pulseG vs inter (parity with text), pulseG15 - pulseG (dose
under guards), cheap C. Writes docs/APPENDIX_PULSE2.md."""

import itertools
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
R = ROOT / "runs/state_pulse"
PREMS = list(range(10))
ARMS = ("habit", "pulse", "inter", "pulseG", "pulseG15")
DIMS = ("surprise", "connection", "coherence")

res = json.loads((R / "rejudge_gen.json").read_text())


def cellmean(prem, arm, dim):
    vals = [r[dim] for r in res if r["cell"] == f"p{prem}_{arm}" and r.get(dim) is not None]
    return float(np.mean(vals)) if vals else None


def paired(arm_a, arm_b, dim):
    ds = []
    for p in PREMS:
        x, y = cellmean(p, arm_a, dim), cellmean(p, arm_b, dim)
        if x is not None and y is not None:
            ds.append(x - y)
    return np.asarray(ds, float)


def signflip(d, alt="greater"):
    n = len(d)
    obs = d.mean()
    if alt == "greater":
        cnt = sum(1 for sg in itertools.product((1, -1), repeat=n)
                  if (d * np.array(sg)).mean() >= obs - 1e-12)
    else:
        cnt = sum(1 for sg in itertools.product((1, -1), repeat=n)
                  if abs((d * np.array(sg)).mean()) >= abs(obs) - 1e-12)
    idx = np.random.default_rng(0).integers(0, n, (10000, n))
    lo, hi = np.percentile(d[idx].mean(1), [2.5, 97.5])
    return obs, float(lo), float(hi), cnt / 2 ** n


L = ["# Appendix — Battery PULSE-2: guards on the pulse "
     "(auto-generated by scripts/analysis_pulse2.py)\n",
     "Pre-registered PLANO 2026-08-30 morning (analysis written before the "
     "data). New arms pulseG (anchor + norm shell, alpha 1.0) and pulseG15 "
     "(alpha 1.5); controls are the PULSO-1 arms (same premises, RNG, "
     "protocol, judge). Unit = premise.\n"]

d_c = paired("pulseG", "pulse", "coherence")
d_s = paired("pulseG", "pulse", "surprise")
obs, lo, hi, p = signflip(d_c, "greater")
guard = float(np.median(d_s))
ok = p < 0.05 and guard > -0.5 and len(d_c) == 10
L.append("## Primary\n")
L.append("| contrast | Δ coherence [CI] | p (one-sided) | surprise guard (median Δ > −0.5) | verdict |")
L.append("|---|---|---|---|---|")
L.append(f"| pulseG − pulse | {obs:+.3f} [{lo:+.3f}, {hi:+.3f}] | {p:.4f} | "
         f"{guard:+.2f} ({'ok' if guard > -0.5 else 'FAIL'}) | "
         f"{'SUPPORTED' if ok else 'not supported'} |")
if len(d_c) < 10:
    L.append(f"\nWARNING: only {len(d_c)} premises complete for the primary.")

L.append("\n## Declared secondaries\n")
L.append("| contrast | dim | Δ [CI] | p (two-sided) |")
L.append("|---|---|---|---|")
for a_, b_ in (("pulseG", "inter"), ("pulseG15", "pulseG")):
    for dim in ("surprise", "coherence"):
        d = paired(a_, b_, dim)
        if len(d):
            o2, lo2, hi2, p2 = signflip(d, "two")
            L.append(f"| {a_} − {b_} | {dim} | {o2:+.3f} [{lo2:+.3f}, {hi2:+.3f}] | {p2:.4f} |")

L.append("\n## Arm means (over premises)\n")
L.append("| arm | surprise | connection | coherence | clean NLL | distinct4 |")
L.append("|---|---|---|---|---|---|")
for arm in ARMS:
    row = [f"| {arm} "]
    for dim in DIMS:
        vs = [cellmean(p_, arm, dim) for p_ in PREMS]
        vs = [v for v in vs if v is not None]
        row.append(f"| {np.mean(vs):.2f} " if vs else "| — ")
    st = [json.loads((R / f"p{p_}_{arm}" / "state.json").read_text())
          for p_ in PREMS if (R / f"p{p_}_{arm}" / "state.json").exists()]
    if st:
        row.append(f"| {np.mean([s['clean_nll_mean'] for s in st]):.2f} "
                   f"| {np.mean([s['distinct4'] for s in st]):.3f} |")
    else:
        row.append("| — | — |")
    L.append("".join(row))

out = ROOT / "docs/APPENDIX_PULSE2.md"
out.write_text("\n".join(L) + "\n")
print("\n".join(L))
print(f"\nwrote {out}")
