#!/usr/bin/env python3
"""Convert the auto-generated markdown appendix tables into LaTeX for the
paper (paper/sections/appendix_tables.tex). Only selected tables are
typeset; the full .md files remain the reference. Numbers are never typed
by hand: they flow from runs/ → analysis scripts → APPENDIX_*.md → here.

    python scripts/appendix_tex.py
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUT = ROOT / "paper" / "sections" / "appendix_tables.tex"


def md_tables(md: str):
    """Yield (heading, header_cells, rows) for every table under a ### heading."""
    heading = None
    lines = md.splitlines()
    i = 0
    while i < len(lines):
        ln = lines[i]
        if ln.startswith("### "):
            heading = ln[4:].strip()
        if ln.startswith("|"):
            block = []
            while i < len(lines) and lines[i].startswith("|"):
                block.append(lines[i]); i += 1
            rows = [[c.strip() for c in r.strip("|").split("|")] for r in block if not re.match(r"^\|[-| ]+\|$", r)]
            if rows:
                yield heading, rows[0], rows[1:]
            continue
        i += 1


def tex_escape(s: str) -> str:
    s = s.replace("\\", "")
    s = s.replace("**", "")
    s = s.replace("&", "\\&").replace("%", "\\%").replace("_", "\\_").replace("#", "\\#")
    s = s.replace("≥", "$\\geq$").replace("≤", "$\\leq$").replace("→", "$\\rightarrow$").replace("−", "$-$").replace("±", "$\\pm$")
    s = s.replace("δ", "$\\delta$").replace("ρ", "$\\rho$").replace("Δ", "$\\Delta$").replace("×", "$\\times$").replace("λ", "$\\lambda$")
    s = s.replace("≈", "$\\approx$").replace("–", "--")
    s = "--" if s.strip() == "—" else s.replace(" — ", ": ").replace("—", ", ")
    return s


def tabular(header, rows, caption, label, small=True, colspec=None):
    n = len(header)
    colspec = colspec or ("l" + "c" * (n - 1))
    out = ["\\begin{table}[H]", "\\centering", "\\scriptsize" if small else "\\small",
           "\\begin{adjustbox}{max width=\\textwidth}",
           f"\\begin{{tabular}}{{@{{}}{colspec}@{{}}}}", "\\toprule",
           " & ".join(tex_escape(h) for h in header) + " \\\\", "\\midrule"]
    for r in rows:
        r = r + [""] * (n - len(r))
        out.append(" & ".join(tex_escape(c) for c in r[:n]) + " \\\\")
    out += ["\\bottomrule", "\\end{tabular}", "\\end{adjustbox}", f"\\caption{{{tex_escape(caption)}}}", f"\\label{{{label}}}", "\\end{table}", ""]
    return "\n".join(out)


def main() -> None:
    parts = ["% auto-generated by scripts/appendix_tex.py - do not edit by hand"]
    # ---- ablation battery
    for heading, header, rows in md_tables((DOCS / "APPENDIX_ANALYSIS.md").read_text()):
        if heading and heading.startswith("Reverie battery"):
            parts.append(tabular(header, rows, "Ablation battery (Qwen3-30B-A3B, 10 seeds, Opus 5 k=5): scaffold vs each condition, unit = window.", "tab:app-ablation"))
        elif heading and heading.startswith("Instrument calibration — three"):
            parts.append(tabular(header, rows, "Instrument calibration: intra-window spread of k=5 judgments per dimension (Opus 5).", "tab:app-calib"))
        elif heading and heading.startswith("Phase 1"):
            parts.append(tabular(header, rows, "Phase 1: objective novelty against the OLMo-2 training corpus (3 prompts × 5 seeds).", "tab:app-phase1"))
        elif heading and heading.startswith("Verified search — Qwen3-30B"):
            parts.append(tabular(header, rows, "Verified search on Qwen3-30B-A3B (bin packing): the anti-probable operator does not separate from plain sampling.", "tab:app-verified"))
    # ---- battery 2
    keep = {"Q1": ("tab:app-q1", "Battery 2, Q1: habituation and interruption (Qwen3-30B-A3B)."),
            "Q2": ("tab:app-q2", "Battery 2, Q2: content of the interruption at period 150."),
            "Q3": ("tab:app-q3", "Battery 2, Q3: timing of the re-encounter, clock vs salience."),
            "Q4 —": ("tab:app-q4", "Battery 2, Q4: frequency of interruption (neutral change)."),
            "Q4b": ("tab:app-q4b", "Battery 2, Q4b: phase within the segment and phase-weighted stream means."),
            "Q5": ("tab:app-q5", "Second generator family (Qwen3-8B-Base)."),
            "Q6": ("tab:app-q6", "Third generator family (OLMo-2-13B).")}
    seen = {}
    for heading, header, rows in md_tables((DOCS / "APPENDIX_B2.md").read_text()):
        if not heading:
            continue
        for k, (label, cap) in keep.items():
            if heading.startswith(k):
                idx = seen.get(k, 0); seen[k] = idx + 1
                suffix = "" if idx == 0 else "-diff"
                cap2 = cap if idx == 0 else cap.rstrip(".") + "; differences vs the reference arm (Δ mean with 95\\% CI over windows; Cliff's δ; Mann--Whitney p; paired-by-seed Δ [CI])."
                colspec = "l" + "c" * (len(header) - 1) if idx == 0 else "p{4.2cm}l" + "c" * (len(header) - 2)
                parts.append(tabular(header, rows, cap2, label + suffix, colspec=colspec))
                break
    # ---- residual stream H1 radii (scaffold set)
    for heading, header, rows in md_tables((DOCS / "APPENDIX_HIDDEN_scaffold.md").read_text()):
        if heading and heading.startswith("H1 —"):
            # too wide: keep condition, n, every other layer, commit, entropy
            idx = [0, 1] + list(range(2, len(header) - 2, 3)) + [len(header) - 2, len(header) - 1]
            h2 = [header[i] for i in idx]; r2 = [[r[i] for i in idx if i < len(r)] for r in rows]
            parts.append(tabular(h2, r2, "Residual-stream geometry (Qwen3-30B-A3B, ablation battery): explored radius per captured layer (subset), stable commitment layer index and final entropy, means over cells.", "tab:app-h1"))
            break
    OUT.write_text("\n".join(p for p in parts if p is not None))
    print("->", OUT.relative_to(ROOT), f"({sum(1 for p in parts if p.startswith(chr(92)+'begin{table}'))} tables)")


if __name__ == "__main__":
    main()
