#!/usr/bin/env python3
"""C-repel (DPO) vs attract (SFT) vs base at cycle 5, held-out variants (R1-R3, PLANO 2026-08-21 23:10)."""
import itertools, json, sys
from pathlib import Path
import numpy as np
ROOT = Path(__file__).resolve().parent.parent; R = ROOT / "runs/dream_c"
sys.path.insert(0, str(ROOT / "scripts"))
from consolidate_analysis import cells, sft_hashes, paired
def load(name):
    f = R / name / "candidates.json"
    return json.loads(f.read_text()) if f.exists() else None
T = {}
for arm, d in (("base", "base_c5"), ("attract", "attract_c5"), ("random", "random_c5"), ("repel", "repel_c5")):
    c = load(d)
    if c:
        T[arm] = cells(c, set())
md = ["# Appendix — C-repel: DPO with the worst candidates as rejected (auto-generated by scripts/consolidate_repel_analysis.py)\n",
      "Held-out variants, cycle-5 seeds; repel adapter trained by DPO (beta 0.1, LoRA rank 8, 16 layers) on pairs chosen = attract set, "
      "rejected = worst valid candidates of the same training variant (cycle-5 attract lineage). Cell = held-out variant.\n",
      "| arm | n cand | mean excess | rel to min(BF,FF) | best | find rate | distinct |", "|---|---|---|---|---|---|---|"]
for arm, ce in T.items():
    m = lambda k: np.mean([v[k] for v in ce.values()])
    md.append(f"| {arm} | {int(sum(v['n'] for v in ce.values()))} | {m('mean'):.4f} | {m('rel'):+.4f} | {m('best'):.4f} | {100*m('find'):.1f}% | {m('distinct'):.2f} |")
md.append("\n| hypothesis | contrast | measure | Δ [CI] | p | n |"); md.append("|---|---|---|---|---|---|")
for hyp, a, b, key, alt in (("R1 (two-sided)", "repel", "attract", "mean", "two-sided"), ("R2", "repel", "base", "best", "less"),
                            ("R2b", "repel", "attract", "best", "less"), ("R3 (two-sided)", "repel", "attract", "distinct", "two-sided"),
                            ("exploratory", "repel", "base", "mean", "less"), ("exploratory", "repel", "random", "mean", "less")):
    if a in T and b in T:
        pr = paired(T[a], T[b], key, alt)
        if pr:
            m_, lo, hi, p, n = pr
            md.append(f"| {hyp} | {a} vs {b} (c5) | {key} | {m_:+.4f} [{lo:+.4f}, {hi:+.4f}] | {p:.4f} | {n} |")
(ROOT / "docs/APPENDIX_C_REPEL.md").write_text("\n".join(md) + "\n"); print("\n".join(md))
