#!/usr/bin/env python3
"""Far transfer (battery C-ext): arms base / attract (final adapter) / random (final adapter)
generated on 6 out-of-family distributions never used in training. Cell = far variant.
F1: attract < base on mean test excess of valid candidates (one-sided); F2: attract < random."""
import itertools, json, sys
from pathlib import Path
import numpy as np
ROOT = Path(__file__).resolve().parent.parent; R = ROOT / "runs/dream_c"
def cells(arm):
    f = R / f"far_{arm}" / "candidates.json"
    if not f.exists(): return {}
    c = json.loads(f.read_text()); out = {}
    for v in range(6):
        cs = [x for x in c.values() if x["which"] == "far" and x["variant"] == v and x["ok"] and x.get("test") is not None]
        if cs:
            out[v] = {"mean": float(np.mean([x["test"] for x in cs])), "best": float(min(x["test"] for x in cs)),
                      "rel": float(np.mean([x["test"] - min(x["bf_test"], x["ff_test"]) for x in cs])), "n": len(cs),
                      "distinct": len({x["hash"] for x in cs}) / len(cs)}
    return out
def paired(a, b, key, alt):
    ks = sorted(set(a) & set(b)); d = np.array([a[k][key] - b[k][key] for k in ks]); n = len(d)
    if n == 0: return None
    obs = d.mean()
    if alt == "less": cnt = sum(1 for sg in itertools.product((1, -1), repeat=n) if (d * np.array(sg)).mean() <= obs + 1e-12)
    else: cnt = sum(1 for sg in itertools.product((1, -1), repeat=n) if abs((d * np.array(sg)).mean()) >= abs(obs) - 1e-12)
    idx = np.random.default_rng(0).integers(0, n, (10000, n)); bs = d[idx].mean(1)
    return obs, np.percentile(bs, 2.5), np.percentile(bs, 97.5), cnt / 2 ** n, n
md = ["# Appendix — Battery C-ext: far transfer (auto-generated by scripts/consolidate_far_analysis.py)\n",
      "Six out-of-family item distributions (Weibull, triangular, bimodal, OR-library), never used in any training set; "
      "arms generated with the final adapters (cycle 5) or none; 3 notebooks x 1,200 tokens per variant. Cell = far variant.\n",
      "| arm | n cand | mean excess | rel to min(BF,FF) | best | distinct |", "|---|---|---|---|---|---|"]
T = {arm: cells(arm) for arm in ("base", "attract", "random")}
for arm, ce in T.items():
    if ce:
        m = lambda k: np.mean([v[k] for v in ce.values()])
        md.append(f"| {arm} | {int(sum(v['n'] for v in ce.values()))} | {m('mean'):.4f} | {m('rel'):+.4f} | {m('best'):.4f} | {m('distinct'):.2f} |")
md.append("\n| hypothesis | contrast | measure | Δ [CI] | p | n |"); md.append("|---|---|---|---|---|---|")
for hyp, a, b, key, alt in (("F1", "attract", "base", "mean", "less"), ("F1b", "attract", "base", "best", "less"),
                            ("F2", "attract", "random", "mean", "less"), ("exploratory", "random", "base", "mean", "two-sided")):
    if T[a] and T[b]:
        pr = paired(T[a], T[b], key, alt)
        if pr: md.append(f"| {hyp} | {a} vs {b} | {key} | {pr[0]:+.4f} [{pr[1]:+.4f}, {pr[2]:+.4f}] | {pr[3]:.4f} | {pr[4]} |")
(ROOT / "docs/APPENDIX_C_FAR.md").write_text("\n".join(md) + "\n"); print("\n".join(md))
