#!/usr/bin/env python3
"""Battery N (tails): do quality-diversity consolidation (qd) and anchored repulsion from the best-fit
clones (repel_mode) keep the tails that attraction/repulsion-from-the-bad erased? Cells = variants
(held-out n=8; far n=6). Metrics per cell: tail = share of valid candidates better than min(BF,FF) on
test; atbf = share exactly at min(BF,FF); levels = distinct test-excess levels / valid; mean; best."""
import itertools, json
from pathlib import Path
import numpy as np
ROOT = Path(__file__).resolve().parent.parent; R = ROOT / "runs/dream_c"
ARMS = {"base": ("base_c5", "far_base"), "attract": ("attract_c5", "far_attract"), "repel_anch": ("repel_anch_c5", "far_repel_anch"),
        "qd": ("qd_c5", "far_qd"), "repel_mode": ("repel_mode_c5", "far_repel_mode")}
def cells(d, which, nv):
    f = R / d / "candidates.json"
    if not f.exists(): return {}
    c = json.loads(f.read_text()); out = {}
    for v in range(nv):
        cs = [x for x in c.values() if x["which"] == which and x["variant"] == v and x["ok"] and x.get("test") is not None]
        if cs:
            ref = [min(x["bf_test"], x["ff_test"]) for x in cs]
            out[v] = {"tail": float(np.mean([x["test"] < r - 1e-9 for x, r in zip(cs, ref)])),
                      "atbf": float(np.mean([abs(x["test"] - r) < 1e-9 for x, r in zip(cs, ref)])),
                      "levels": len({round(x["test"], 6) for x in cs}) / len(cs),
                      "mean": float(np.mean([x["test"] for x in cs])), "best": float(min(x["test"] for x in cs)), "n": len(cs)}
    return out
def paired(a, b, key, alt):
    ks = sorted(set(a) & set(b)); d = np.array([a[k][key] - b[k][key] for k in ks]); n = len(d)
    if n == 0: return None
    obs = d.mean()
    if alt == "greater": cnt = sum(1 for sg in itertools.product((1, -1), repeat=n) if (d * np.array(sg)).mean() >= obs - 1e-12)
    elif alt == "less": cnt = sum(1 for sg in itertools.product((1, -1), repeat=n) if (d * np.array(sg)).mean() <= obs + 1e-12)
    else: cnt = sum(1 for sg in itertools.product((1, -1), repeat=n) if abs((d * np.array(sg)).mean()) >= abs(obs) - 1e-12)
    idx = np.random.default_rng(0).integers(0, n, (10000, n)); bs = d[idx].mean(1)
    return obs, np.percentile(bs, 2.5), np.percentile(bs, 97.5), cnt / 2 ** n, n
md = ["# Appendix — Battery N: keeping the tails (auto-generated by scripts/consolidate_tails_analysis.py)\n",
      "tail = share of valid candidates better than the better classic heuristic (test); atbf = share exactly at that level; "
      "levels = distinct score levels per valid candidate (functional diversity). Cells = variants.\n"]
T = {}
for which, nv in (("heldout", 8), ("far", 6)):
    md.append(f"\n## {which}\n"); md.append("| arm | n cand | tail | at classic | levels | mean | best |"); md.append("|---|---|---|---|---|---|---|")
    for arm, (dh, df) in ARMS.items():
        ce = cells(dh if which == "heldout" else df, which, nv); T[(arm, which)] = ce
        if ce:
            m = lambda k: np.mean([v[k] for v in ce.values()])
            md.append(f"| {arm} | {int(sum(v['n'] for v in ce.values()))} | {100*m('tail'):.1f}% | {100*m('atbf'):.0f}% | {m('levels'):.2f} | {m('mean'):.4f} | {m('best'):.4f} |")
md.append("\n## Pre-registered contrasts\n"); md.append("| hypothesis | contrast | where | measure | Δ [CI] | p | n |"); md.append("|---|---|---|---|---|---|---|")
for hyp, a, b, which, key, alt in (("T1 (primary)", "qd", "attract", "far", "tail", "greater"), ("T1b", "repel_mode", "repel_anch", "far", "tail", "greater"),
                                   ("T1c", "qd", "attract", "heldout", "tail", "greater"),
                                   ("T2", "qd", "attract", "heldout", "atbf", "less"), ("T2b", "repel_mode", "repel_anch", "heldout", "atbf", "less"),
                                   ("T2c levels", "qd", "attract", "heldout", "levels", "greater"), ("T2d levels", "repel_mode", "repel_anch", "heldout", "levels", "greater"),
                                   ("T3 (two-sided)", "qd", "attract", "heldout", "mean", "two-sided"), ("T3b (two-sided)", "repel_mode", "repel_anch", "heldout", "mean", "two-sided"),
                                   ("T4", "qd", "base", "far", "best", "less"), ("T4b", "repel_mode", "base", "far", "best", "less")):
    A, B = T.get((a, which), {}), T.get((b, which), {})
    if A and B:
        pr = paired(A, B, key, alt)
        if pr: md.append(f"| {hyp} | {a} vs {b} | {which} | {key} | {pr[0]:+.4f} [{pr[1]:+.4f}, {pr[2]:+.4f}] | {pr[3]:.4f} | {pr[4]} |")
(ROOT / "docs/APPENDIX_N.md").write_text("\n".join(md) + "\n"); print("\n".join(md))
