#!/usr/bin/env python3
"""Battery C analysis (pre-registered C1-C4, docs/PLANO.md 2026-08-21). Transfer is
measured on the HELD-OUT variants (never in any SFT set), test instances (seeds 200+).
Cell = held-out variant (n=8); exact sign-flip permutation on paired cell means.
Writes docs/APPENDIX_C.md."""
import itertools, json, sys, hashlib, re
from pathlib import Path
import numpy as np
ROOT = Path(__file__).resolve().parent.parent
R = ROOT / "runs/dream_c"
sys.path.insert(0, str(ROOT / "scripts"))

def norm(code):
    body = "\n".join(l.strip() for l in code.splitlines()[1:] if l.strip() and not l.strip().startswith('"""'))
    return hashlib.md5(re.sub(r"\s+", " ", body).encode()).hexdigest()

def load(arm, k):
    f = R / f"{arm}_c{k}" / "candidates.json"
    return json.loads(f.read_text()) if f.exists() else None

def sft_hashes(arm, k):
    f = R / f"sft_{arm}_c{k}" / "train.jsonl"
    if not f.exists():
        return set()
    return {norm(json.loads(l)["completion"]) for l in f.read_text().splitlines() if l.strip()}

def cells(cands, trained):
    """per held-out variant: mean test excess of valid candidates, best, find rate, distinct ratio, copy share, n"""
    out = {}
    for v in range(8):
        cs = [c for c in cands.values() if c["which"] == "heldout" and c["variant"] == v and c["ok"] and c.get("test") is not None]
        if not cs:
            continue
        hs = [c["hash"] for c in cs]
        out[v] = {"mean": float(np.mean([c["test"] for c in cs])), "best": float(min(c["test"] for c in cs)),
                  "find": float(np.mean([bool(c.get("find")) for c in cs])), "distinct": len(set(hs)) / len(hs),
                  "copy": float(np.mean([h in trained for h in hs])), "n": len(cs),
                  "rel": float(np.mean([c["test"] - min(c["bf_test"], c["ff_test"]) for c in cs]))}
    return out

def boot(x, n=10000):
    x = np.asarray(x, float); idx = np.random.default_rng(0).integers(0, len(x), (n, len(x)))
    return np.percentile(x[idx].mean(1), 2.5), np.percentile(x[idx].mean(1), 97.5)

def paired(a, b, key, alt):
    ks = sorted(set(a) & set(b)); d = np.array([a[k][key] - b[k][key] for k in ks], float); n = len(d)
    if n == 0:
        return None
    if alt == "less":
        obs = d.mean(); cnt = sum(1 for sg in itertools.product((1, -1), repeat=n) if (d * np.array(sg)).mean() <= obs + 1e-12)
    elif alt == "greater":
        obs = d.mean(); cnt = sum(1 for sg in itertools.product((1, -1), repeat=n) if (d * np.array(sg)).mean() >= obs - 1e-12)
    else:
        obs = abs(d.mean()); cnt = sum(1 for sg in itertools.product((1, -1), repeat=n) if abs((d * np.array(sg)).mean()) >= obs - 1e-12)
    lo, hi = boot(d) if n > 1 else (d.mean(), d.mean())
    return d.mean(), lo, hi, cnt / 2 ** n, n

md = ["# Appendix — Battery C: consolidation by LoRA (auto-generated by scripts/consolidate_analysis.py)\n",
      "Qwen3-8B-Base (8-bit), small-item bin-packing family. Transfer measured on 8 held-out variants (never in any "
      "training set), test instances (20 x 200 items, seeds 200+). mean/best = test excess over the lower bound of valid "
      "candidates; rel = mean excess minus min(best fit, first fit); find = share beating min(BF, FF) on the variant's "
      "own training instances by 0.001; distinct = distinct/valid; copy = share identical (normalized) to a function in "
      "the arm's SFT set of that cycle. Cell = held-out variant; paired exact sign-flip tests over variants.\n",
      "| arm | cycle | n cand | mean excess | rel to min(BF,FF) | best | find rate | distinct | copy |", "|---|---|---|---|---|---|---|---|---|"]
table = {}
for k in range(0, 6):
    for arm in ("base", "attract", "random"):
        c = load(arm, k)
        if c is None:
            continue
        ce = cells(c, sft_hashes(arm, k)); table[(arm, k)] = ce
        if not ce:
            continue
        m = lambda key: np.mean([v[key] for v in ce.values()])
        md.append(f"| {arm} | {k} | {int(sum(v['n'] for v in ce.values()))} | {m('mean'):.4f} | {m('rel'):+.4f} | {m('best'):.4f} | {100*m('find'):.1f}% | {m('distinct'):.2f} | {100*m('copy'):.0f}% |")
ks = sorted({k for (_, k) in table if k > 0})
if ks:
    K = max(ks)
    md.append(f"\n### Pre-registered contrasts at the final cycle (k = {K}); cells = held-out variants\n")
    md.append("| hypothesis | contrast | measure | Δ [CI] | p | n |"); md.append("|---|---|---|---|---|---|")
    for hyp, a, b, key, alt in (("C1 (primary)", "attract", "base", "mean", "less"), ("C1b", "attract", "base", "best", "less"),
                                ("C2", "attract", "random", "mean", "less"), ("C2b", "attract", "random", "best", "less"),
                                ("C3", "attract", "base", "find", "greater"), ("C3b", "attract", "random", "find", "greater"),
                                ("C4 (two-sided)", "attract", "base", "distinct", "two-sided"), ("C4b (two-sided)", "attract", "random", "distinct", "two-sided"),
                                ("exploratory", "random", "base", "mean", "two-sided")):
        A, B = table.get((a, K)), table.get((b, K))
        if A and B:
            pr = paired(A, B, key, alt)
            if pr:
                m_, lo, hi, p, n = pr
                md.append(f"| {hyp} | {a} vs {b} (c{K}) | {key} | {m_:+.4f} [{lo:+.4f}, {hi:+.4f}] | {p:.4f} | {n} |")
    md.append("\n### Trajectory: attract vs base per cycle (mean excess on held-out variants; paired)\n")
    md.append("| cycle | Δ mean (attract − base) [CI] | p (less) | Δ find rate | Δ distinct |"); md.append("|---|---|---|---|---|")
    for k in ks:
        A, B = table.get(("attract", k)), table.get(("base", k))
        if A and B:
            pm = paired(A, B, "mean", "less"); pf = paired(A, B, "find", "greater"); pd = paired(A, B, "distinct", "two-sided")
            md.append(f"| {k} | {pm[0]:+.4f} [{pm[1]:+.4f}, {pm[2]:+.4f}] | {pm[3]:.4f} | {pf[0]:+.3f} | {pd[0]:+.2f} |")
(ROOT / "docs/APPENDIX_C.md").write_text("\n".join(md) + "\n"); print("\n".join(md))
