#!/usr/bin/env python3
"""Battery S analysis: pre-registered contrasts (docs/PLANO.md, 2026-08-19 20:30).
S1 (primary, one-sided): champion held-out gain over best fit, angle > plain.
S2 (one-sided): cumulative distinct valid candidates, angle > plain.
S3 (two-sided): escape generation. S4 exploratory. Writes docs/APPENDIX_S.md."""
import itertools, json
from pathlib import Path
import numpy as np
ROOT = Path(__file__).resolve().parent.parent
h = json.loads((ROOT / "runs/evointerrupt/history.json").read_text())
def cell(arm, key):
    out = {}
    for k, v in h.items():
        if v["arm"] != arm: continue
        if key == "gain":
            ct = v["champion_test_excess"]
            ct = v["bf_test"] if (ct is None or (isinstance(ct, float) and np.isnan(ct))) else ct  # nan champion: count as best fit (it was in the population)
            out[v["variant"]] = v["bf_test"] - ct
        elif key == "distinct": out[v["variant"]] = v["distinct_total"]
        elif key == "escape": out[v["variant"]] = v["escape_gen"] if v["escape_gen"] is not None else 8
        elif key == "beats": out[v["variant"]] = int(v["champion_test_excess"] is not None and v["champion_test_excess"] < v["bf_test"] - 1e-9)
    return out
def boot(x, n=10000):
    x = np.asarray(x, float); rng = np.random.default_rng(0); idx = rng.integers(0, len(x), (n, len(x)))
    return np.percentile(x[idx].mean(1), 2.5), np.percentile(x[idx].mean(1), 97.5)
def paired(a, b, alt):
    ks = sorted(set(a) & set(b)); d = np.array([a[k] - b[k] for k in ks], float); n = len(d)
    if alt == "greater":
        obs = d.mean(); cnt = sum(1 for sg in itertools.product((1,-1), repeat=n) if (d*np.array(sg)).mean() >= obs - 1e-12)
    else:
        obs = abs(d.mean()); cnt = sum(1 for sg in itertools.product((1,-1), repeat=n) if abs((d*np.array(sg)).mean()) >= obs - 1e-12)
    lo, hi = boot(d); return d.mean(), lo, hi, cnt/2**n, n
md = ["# Appendix — Battery S: the interruption inside a selection loop (auto-generated by scripts/evolve_interrupt_analysis.py)\n",
      "FunSearch-style evolution, 10 variants x 2 arms x 8 generations x 16 samples, plain sampler, paired by variant. "
      "gain = best-fit held-out excess minus the champion's (higher is better; a champion that fails on test counts as best fit); "
      "distinct = cumulative distinct valid candidates; escape = first generation whose best train excess beats best fit (8 = never).\n",
      "| arm | mean gain [CI] | mean distinct | mean escape gen | cells beating best fit on test |", "|---|---|---|---|---|"]
for arm in ("plain", "angle"):
    g = cell(arm, "gain"); lo, hi = boot(list(g.values()))
    md.append(f"| {arm} | {np.mean(list(g.values())):+.4f} [{lo:+.4f}, {hi:+.4f}] | {np.mean(list(cell(arm,'distinct').values())):.1f} | "
              f"{np.mean(list(cell(arm,'escape').values())):.1f} | {sum(cell(arm,'beats').values())}/10 |")
md.append("\n| hypothesis | measure | Δ (angle − plain) [CI] | p | n |"); md.append("|---|---|---|---|---|")
for hyp, key, alt in (("S1 (primary)", "gain", "greater"), ("S2", "distinct", "greater"), ("S3 (two-sided)", "escape", "two-sided"), ("exploratory", "beats", "two-sided")):
    m, lo, hi, p, n = paired(cell("angle", key), cell("plain", key), alt)
    md.append(f"| {hyp} | {key} | {m:+.4f} [{lo:+.4f}, {hi:+.4f}] | {p:.4f} | {n} |")
(ROOT / "docs/APPENDIX_S.md").write_text("\n".join(md) + "\n"); print("\n".join(md))
