#!/usr/bin/env python3
"""Battery F analysis (pre-registered F1-F5, PLANO 2026-08-22 16:10): per run (problem x arm) from history.jsonl:
frac = (best - seed)/(record - seed) in the problem's direction; auc = mean frac of best-so-far over the sample
budget; div = distinct behaviours / valid; valid share; record beaten. Cells = problems; exact sign-flip tests."""
import itertools, json, sys
from pathlib import Path
import numpy as np
ROOT = Path(__file__).resolve().parent.parent; R = ROOT / "runs/frontier/F"
sys.path.insert(0, str(ROOT / "scripts"))
from frontier_search import PROBLEMS
ARMS = ["A", "B", "C", "D", "E"]
def seed_score(P):
    sys.path.insert(0, str(ROOT / "src"))
    from creative_machine.frontier_exec import run_candidate
    return run_candidate(P["seed_program"], P["module"], P["entry"], P["args"])["score"]
def metrics(prob, arm, budget=120):
    f = R / f"{prob}_{arm}" / "history.jsonl"
    if not f.exists(): return None
    P = PROBLEMS[prob]; rows = [json.loads(l) for l in f.read_text().splitlines() if l.strip()][:budget]
    if not rows: return None
    s0 = SEED[prob]; rec = P["best_known"]; sgn = 1 if P["maximize"] else -1
    best = s0; fr = []
    for r in rows:
        if r.get("ok") and (sgn * (r["score"] - best) > 0): best = r["score"]
        fr.append((sgn * (best - s0)) / max(1e-12, sgn * (rec - s0)))
    ok = [r for r in rows if r.get("ok")]
    return {"frac": fr[-1], "auc": float(np.mean(fr)), "div": (len({r.get("sig") for r in ok}) / len(ok)) if ok else 0.0,
            "valid": len(ok) / len(rows), "best": best, "record": fr[-1] > 1.0, "n": len(rows)}
def paired(a, b, key, alt):
    ks = sorted(set(a) & set(b)); d = np.array([a[k][key] - b[k][key] for k in ks]); n = len(d)
    if n == 0: return None
    obs = d.mean()
    if alt == "greater": cnt = sum(1 for sg in itertools.product((1, -1), repeat=n) if (d * np.array(sg)).mean() >= obs - 1e-12)
    else: cnt = sum(1 for sg in itertools.product((1, -1), repeat=n) if abs((d * np.array(sg)).mean()) >= abs(obs) - 1e-12)
    idx = np.random.default_rng(0).integers(0, n, (10000, n)); bs = d[idx].mean(1)
    return obs, np.percentile(bs, 2.5), np.percentile(bs, 97.5), cnt / 2 ** n, n
SEED = {p: seed_score(P) for p, P in PROBLEMS.items()}
T = {arm: {} for arm in ARMS}
md = ["# Appendix — Battery F: cognitive operators inside verified search (auto-generated by scripts/frontier_analysis.py)\n",
      "Arms: A = standard loop; B = schematic notebook memory; C = agenda (named obstacle); D = behavioural repulsion "
      "(novelty by construction + repulsor prompt); E = B+C+D. Budget 120 samples per run (10 gens x 2 islands x 6). "
      "frac = fraction of the way from the seed to the best-known record (>1 = record beaten); auc = mean frac of "
      "best-so-far over the budget; div = distinct behaviours / valid. Cells = problems.\n",
      "| problem | arm | samples | valid | best | frac | auc | div | record? |", "|---|---|---|---|---|---|---|---|---|"]
for prob in PROBLEMS:
    for arm in ARMS:
        m = metrics(prob, arm)
        if m:
            T[arm][prob] = m
            md.append(f"| {prob} | {arm} | {m['n']} | {100*m['valid']:.0f}% | {m['best']:.6f} | {m['frac']:.3f} | {m['auc']:.3f} | {m['div']:.2f} | {'YES' if m['record'] else 'no'} |")
md.append("\n## Pre-registered contrasts (cells = problems)\n"); md.append("| hypothesis | contrast | measure | Δ [CI] | p | n |"); md.append("|---|---|---|---|---|---|")
for hyp, a, b, key, alt in (("F1 (primary)", "E", "A", "frac", "greater"), ("F2", "E", "A", "auc", "greater"),
                            ("F3 B", "B", "A", "frac", "greater"), ("F3 C", "C", "A", "frac", "greater"), ("F3 D", "D", "A", "frac", "greater"),
                            ("F3 B auc", "B", "A", "auc", "greater"), ("F3 C auc", "C", "A", "auc", "greater"), ("F3 D auc", "D", "A", "auc", "greater"),
                            ("F4", "D", "A", "div", "greater"), ("F4b", "E", "A", "div", "greater")):
    pr = paired(T[a], T[b], key, alt)
    if pr: md.append(f"| {hyp} | {a} vs {b} | {key} | {pr[0]:+.3f} [{pr[1]:+.3f}, {pr[2]:+.3f}] | {pr[3]:.4f} | {pr[4]} |")
(ROOT / "docs/APPENDIX_F.md").write_text("\n".join(md) + "\n"); print("\n".join(md))
