#!/usr/bin/env python3
"""Battery V analysis (pre-registered V1-V4, docs/PLANO.md 2026-08-20 20:15).
Arms fb300/fbagenda from runs/dream_v/*/cells.json; baselines plain/angle300
from battery B (runs/dream_problem, runs/dream_problem_r1), their candidates
re-scored on train IN TEXT ORDER for the progression metric. Cell = variant
(mean over the 2 RNG seeds). Writes docs/APPENDIX_V.md."""
import hashlib, itertools, json, re, sys
from pathlib import Path
import numpy as np
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src")); sys.path.insert(0, str(ROOT / "scripts"))
from creative_machine.code_exec import run_heuristic_code
from creative_machine.domains.binpack import generate_instances
from creative_machine.problem_premises import VARIANTS
from problem_loop import closed_functions, BEST_FIT_CODE

def norm(code):
    body = "\n".join(l.strip() for l in code.splitlines()[1:] if l.strip() and not l.strip().startswith('"""'))
    return hashlib.md5(re.sub(r"\s+", " ", body).encode()).hexdigest()

CACHE = ROOT / "runs/dream_v/b_rescore_cache.json"
cache = json.loads(CACHE.read_text()) if CACHE.exists() else {}

def eval_sources(sources, vi):
    lo, hi = VARIANTS[vi]
    train = generate_instances(5, 100, np.random.default_rng(100 + vi), lo, hi)
    test = generate_instances(5, 100, np.random.default_rng(200 + vi), lo, hi)
    bf_te = run_heuristic_code(BEST_FIT_CODE, test)["mean_excess"]
    best_tr, improvements, valid, hashes, best_te = None, 0, 0, set(), None
    for src in sources:
        r = run_heuristic_code(src, train, timeout_s=15.0)
        if not r.get("ok"):
            continue
        valid += 1; hashes.add(norm(src))
        x = r["mean_excess"]
        if best_tr is None or x < best_tr - 1e-9:
            if best_tr is not None: improvements += 1
            best_tr = x
        rt = run_heuristic_code(src, test, timeout_s=15.0)
        if rt.get("ok") and (best_te is None or rt["mean_excess"] < best_te - 1e-9):
            best_te = rt["mean_excess"]
    gain = bf_te - (best_te if best_te is not None else run_heuristic_code("def priority(item: float, remaining: list[float]) -> list[float]:\n    return [0.0] * len(remaining)\n", test)["mean_excess"])
    return {"gain": gain, "improvements": improvements, "valid": valid, "distinct": len(hashes)}

cells = {}   # (arm, variant) -> list of per-rng dicts
# V arms
for d in sorted((ROOT / "runs/dream_v").glob("*_r[01]")):
    arm, rng = d.name.rsplit("_r", 1)
    cj = json.loads((d / "cells.json").read_text())
    for k, v in cj.items():
        key = f"{d.name}/{k}"
        if key not in cache:
            cache[key] = eval_sources(v["sources"], v["variant"]); CACHE.write_text(json.dumps(cache))
        m = dict(cache[key]); m["fabricated"] = None
        txt = (d / f"{k}.txt").read_text()
        n_lines = sum(1 for l in txt.splitlines() if l.startswith("# Verifier:"))
        m["fabricated"] = max(0, n_lines - len(v["results"]))
        cells.setdefault((arm, v["variant"]), []).append(m)
# B baselines
for run, rng in (("dream_problem", 0), ("dream_problem_r1", 1)):
    for d in sorted((ROOT / "runs" / run).glob("s*_*")):
        if not (d / "text.txt").exists(): continue
        vi = int(d.name.split("_", 1)[0][1:]); cond = d.name.split("_", 1)[1]
        if cond not in ("plain", "angle300"): continue
        key = f"{run}/{d.name}"
        if key not in cache:
            srcs = [s for _, s in closed_functions((d / "text.txt").read_text())]
            cache[key] = eval_sources(srcs, vi); CACHE.write_text(json.dumps(cache))
        cells.setdefault((cond, vi), []).append(dict(cache[key]))

def cellv(arm, key):
    return {v: float(np.mean([r[key] for r in rs])) for (a, v), rs in cells.items() if a == arm and rs}
def boot(x, n=10000):
    x = np.asarray(x, float); rng = np.random.default_rng(0); idx = rng.integers(0, len(x), (n, len(x)))
    return np.percentile(x[idx].mean(1), 2.5), np.percentile(x[idx].mean(1), 97.5)
def paired(a, b, alt):
    ks = sorted(set(a) & set(b)); d = np.array([a[k] - b[k] for k in ks], float); n = len(d)
    if alt == "greater":
        obs = d.mean(); cnt = sum(1 for sg in itertools.product((1, -1), repeat=n) if (d * np.array(sg)).mean() >= obs - 1e-12)
    else:
        obs = abs(d.mean()); cnt = sum(1 for sg in itertools.product((1, -1), repeat=n) if abs((d * np.array(sg)).mean()) >= obs - 1e-12)
    lo, hi = boot(d); return d.mean(), lo, hi, cnt / 2 ** n, n

md = ["# Appendix — Battery V: the verifier inside the loop (auto-generated by scripts/problem_loop_analysis.py)\n",
      "Event-driven verifier feedback injected into the notebook (fb300), plus a deterministic scoreboard every 300 tokens "
      "(fbagenda); baselines are battery B's plain and angle arms re-scored in text order. Cell = variant (mean over 2 RNG "
      "seeds). gain = best-fit held-out excess minus the notebook's best (higher is better); improvements = candidates that "
      "beat the notebook's own training best so far (the verifier's measure of progression); fabricated = '# Verifier:' "
      "lines written by the model itself.\n",
      "| arm | n | gain [CI] | improvements | valid | distinct | fabricated verdicts |", "|---|---|---|---|---|---|---|"]
for arm in ("plain", "angle300", "fb300", "fbagenda"):
    g = cellv(arm, "gain")
    if not g: continue
    lo, hi = boot(list(g.values()))
    fab = cellv(arm, "fabricated") if (arm, 0) in cells and "fabricated" in cells[(arm, 0)][0] else {}
    md.append(f"| {arm} | {len(g)} | {np.mean(list(g.values())):+.4f} [{lo:+.4f}, {hi:+.4f}] | "
              f"{np.mean(list(cellv(arm,'improvements').values())):.1f} | {np.mean(list(cellv(arm,'valid').values())):.1f} | "
              f"{np.mean(list(cellv(arm,'distinct').values())):.1f} | " + (f"{np.mean(list(fab.values())):.1f} |" if fab else "— |"))
md.append("\n| hypothesis | contrast | measure | Δ [CI] | p | n |"); md.append("|---|---|---|---|---|---|")
for hyp, a, b, key, alt in (("V1 (primary)", "fb300", "angle300", "gain", "greater"),
                            ("V2", "fb300", "angle300", "improvements", "greater"),
                            ("V3 (two-sided)", "fb300", "angle300", "valid", "two-sided"),
                            ("V3 (two-sided)", "fb300", "angle300", "distinct", "two-sided"),
                            ("V4", "fbagenda", "fb300", "gain", "greater"),
                            ("V4", "fbagenda", "fb300", "improvements", "greater"),
                            ("exploratory", "fb300", "plain", "improvements", "two-sided"),
                            ("exploratory", "fbagenda", "angle300", "improvements", "two-sided")):
    A, B = cellv(a, key), cellv(b, key)
    if A and B:
        m, lo, hi, p, n = paired(A, B, alt)
        md.append(f"| {hyp} | {a} vs {b} | {key} | {m:+.4f} [{lo:+.4f}, {hi:+.4f}] | {p:.4f} | {n} |")
(ROOT / "docs/APPENDIX_V.md").write_text("\n".join(md) + "\n"); print("\n".join(md))
