#!/usr/bin/env python3
"""Battery B, combined analysis: cell value = mean over the RNG seeds (runs) per variant;
pre-registered contrasts (docs/PLANO.md): B1 angle300 > plain on gain (one-sided), B2 angle300 > plain
on distinct valid candidates (one-sided), B3 angle300 vs reset300 on gain (two-sided), B4 sham300 = plain.
Writes docs/APPENDIX_PROBLEM.md."""
import itertools, json, sys
from pathlib import Path
import numpy as np
ROOT = Path(__file__).resolve().parent.parent
RUNS = [ROOT / "runs/dream_problem", ROOT / "runs/dream_problem_r1"]
ARMS = ["plain", "sham300", "angle300", "reset300"]
KEYS = ("gain", "valid", "distinct", "beats", "cands")
cells = {}  # (arm, variant) -> list of per-run dicts
for rd in RUNS:
    v = json.loads((rd / "verified.json").read_text())
    for name, rec in v.items():
        best = rec["best_held_excess"] if rec["best_held_excess"] is not None else rec["baselines"]["first_fit"]
        cells.setdefault((rec["cond"], rec["variant"]), []).append({
            "gain": rec["baselines"]["best_fit"] - best, "valid": rec["n_valid"], "distinct": rec["n_distinct_valid"],
            "beats": int(rec["beats_best_fit"]), "cands": rec["n_candidates"], "best": best, "bf": rec["baselines"]["best_fit"]})
def cellval(arm, key):
    return {var: float(np.mean([r[key] for r in rs])) for (a, var), rs in cells.items() if a == arm}
def boot(x, n=10000):
    x = np.asarray(x, float); rng = np.random.default_rng(0); idx = rng.integers(0, len(x), (n, len(x))); m = x[idx].mean(1)
    return np.percentile(m, 2.5), np.percentile(m, 97.5)
def paired(a, b, alt="two-sided"):
    ks = sorted(set(a) & set(b)); d = np.array([a[k] - b[k] for k in ks]); n = len(d)
    if alt == "greater":
        obs = d.mean(); cnt = sum(1 for s in itertools.product((1, -1), repeat=n) if (d * np.array(s)).mean() >= obs - 1e-12)
    else:
        obs = abs(d.mean()); cnt = sum(1 for s in itertools.product((1, -1), repeat=n) if abs((d * np.array(s)).mean()) >= obs - 1e-12)
    lo, hi = boot(d); return d.mean(), lo, hi, cnt / 2 ** n, n
md = ["# Appendix — Battery B: the interrupted loop over a problem with a verifier (auto-generated by scripts/problem_analysis.py)\n",
      "Online bin packing notebook, Qwen3-30B-A3B-Base, 10 size-distribution variants x 2 RNG seeds per arm; cell = variant "
      "(mean over the 2 seeds). gain = best-fit excess minus the best held-out excess among the stream's valid candidates "
      "(higher is better; a stream with no valid candidate counts as first fit); valid/distinct = valid (distinct) `priority` "
      "functions written and verified; beats = share of cells whose best candidate beats best fit on held-out instances.\n",
      "| arm | n | candidates | valid | distinct valid | gain over best fit [CI] | cells beating best fit |", "|---|---|---|---|---|---|---|"]
for arm in ARMS:
    g = cellval(arm, "gain"); lo, hi = boot(list(g.values()))
    md.append(f"| {arm} | {len(g)} | {np.mean(list(cellval(arm,'cands').values())):.1f} | {np.mean(list(cellval(arm,'valid').values())):.1f} | "
              f"{np.mean(list(cellval(arm,'distinct').values())):.1f} | {np.mean(list(g.values())):+.4f} [{lo:+.4f}, {hi:+.4f}] | {np.mean(list(cellval(arm,'beats').values()))*100:.0f}% |")
md.append("\n## Pre-registered contrasts (exact sign-flip permutation; one-sided where pre-specified)\n")
md.append("| hypothesis | contrast | measure | Δ [CI] | p | n |"); md.append("|---|---|---|---|---|---|")
for hyp, a, b, key, alt in (("B1 (primary)", "angle300", "plain", "gain", "greater"), ("B2", "angle300", "plain", "distinct", "greater"),
                            ("B3 (two-sided)", "angle300", "reset300", "gain", "two-sided"), ("B4 (two-sided)", "sham300", "plain", "gain", "two-sided"),
                            ("exploratory", "reset300", "plain", "gain", "two-sided"), ("exploratory", "reset300", "plain", "distinct", "two-sided"),
                            ("exploratory", "angle300", "plain", "valid", "two-sided"), ("exploratory", "angle300", "sham300", "distinct", "two-sided")):
    m, lo, hi, p, n = paired(cellval(a, key), cellval(b, key), alt)
    md.append(f"| {hyp} | {a} vs {b} | {key} | {m:+.4f} [{lo:+.4f}, {hi:+.4f}] | {p:.4f} | {n} |")
# how far below best fit: per arm, the best candidate vs best fit, and the number of cells where at least one candidate ties best fit
md.append("\n## Best candidate against the baselines (held-out)\n")
md.append("| arm | mean best excess | mean best-fit excess | cells with best == best fit (within 1e-9) | cells with best < best fit |")
md.append("|---|---|---|---|---|")
for arm in ARMS:
    rs = [r for (a, v), lst in cells.items() if a == arm for r in lst]
    md.append(f"| {arm} | {np.mean([r['best'] for r in rs]):.4f} | {np.mean([r['bf'] for r in rs]):.4f} | {sum(abs(r['best']-r['bf'])<1e-9 for r in rs)}/{len(rs)} | {sum(r['best']<r['bf']-1e-9 for r in rs)}/{len(rs)} |")
(ROOT / "docs/APPENDIX_PROBLEM.md").write_text("\n".join(md) + "\n"); print("\n".join(md))
