#!/usr/bin/env python3
"""Spectral summary per arm (paper-4 review, Q4): reads every runs/spectral/
<run>__<cell>.npz written by spectral.py, takes the dominant detrended peak of
the state, token and sentence-boundary autocorrelations, and reports per arm
the mean prominence and period with bootstrap CIs over cells, plus the
sentence-rhythm check (is the state period the punctuation period?).
Writes docs/APPENDIX_SPECTRA.md.

    python scripts/spectral_summary.py --run state_pulse [--run r4]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
from spectral import dominant  # noqa: E402


def ci(vals, stat=np.mean):
    v = np.asarray(vals, float)
    if len(v) == 0:
        return float("nan"), float("nan"), float("nan")
    idx = np.random.default_rng(0).integers(0, len(v), (10000, len(v)))
    boots = np.array([stat(v[i]) for i in idx])
    return float(stat(v)), float(np.percentile(boots, 2.5)), float(np.percentile(boots, 97.5))


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--run", action="append", default=None, help="run dir name(s) to summarise (default: all)")
    p.add_argument("--spectral", type=Path, default=ROOT / "runs/spectral")
    args = p.parse_args()
    files = sorted(args.spectral.glob("*.npz"))
    rows = []
    for f in files:
        run, cell = f.stem.split("__", 1)
        if args.run and run not in args.run:
            continue
        z = np.load(f)
        ps, prs = dominant(z["a_state"])
        pt, prt = dominant(z["a_tok"])
        pp, prp = dominant(z["a_punct"]) if "a_punct" in z else (None, None)
        arm = cell.split("_", 1)[1] if "_" in cell else cell
        rows.append({"run": run, "cell": cell, "arm": arm, "P_state": ps, "prom_state": prs,
                     "P_tok": pt, "prom_tok": prt, "P_punct": pp, "prom_punct": prp})
    L = ["# Appendix — Spectra per arm (auto-generated by scripts/spectral_summary.py)\n",
         "Detrended local-peak reader (spectral.py); unit = cell; bootstrap CIs over cells. "
         "`punct` = autocorrelation of the sentence-boundary indicator (tokens containing . ! ? or a newline): "
         "the rhythm of sentences, the null the state period must beat to count as an orbit.\n"]
    for run in sorted({r["run"] for r in rows}):
        L.append(f"## {run}\n")
        L.append("| arm | n | state prominence [CI] | state period (median) | token prominence [CI] | punct prominence [CI] | punct period (median) | cells with P_state within 20% of P_punct |")
        L.append("|---|---|---|---|---|---|---|---|")
        arms = sorted({r["arm"] for r in rows if r["run"] == run})
        for arm in arms:
            rs = [r for r in rows if r["run"] == run and r["arm"] == arm]
            m, lo, hi = ci([r["prom_state"] for r in rs])
            mt, lot, hit = ci([r["prom_tok"] for r in rs])
            has_p = [r for r in rs if r["P_punct"] is not None]
            mp, lop, hip = ci([r["prom_punct"] for r in has_p]) if has_p else (float("nan"),) * 3
            pp_med = np.median([r["P_punct"] for r in has_p]) if has_p else float("nan")
            near = [abs(r["P_state"] - r["P_punct"]) <= 0.2 * max(1, r["P_punct"]) for r in has_p if r["P_punct"]]
            L.append(f"| {arm} | {len(rs)} | {m:.3f} [{lo:.3f}, {hi:.3f}] | {np.median([r['P_state'] for r in rs]):.0f} "
                     f"| {mt:.3f} [{lot:.3f}, {hit:.3f}] | {mp:.3f} [{lop:.3f}, {hip:.3f}] | {pp_med:.0f} "
                     f"| {sum(near)}/{len(near)} |")
        L.append("")
        L.append("### Per cell\n")
        L.append("| cell | P_state | prom_state | P_tok | prom_tok | P_punct | prom_punct |")
        L.append("|---|---|---|---|---|---|---|")
        for r in sorted((r for r in rows if r["run"] == run), key=lambda r: r["cell"]):
            L.append(f"| {r['cell']} | {r['P_state']} | {r['prom_state']:.3f} | {r['P_tok']} | {r['prom_tok']:.3f} "
                     f"| {r['P_punct'] if r['P_punct'] is not None else '—'} | "
                     f"{r['prom_punct']:.3f} |" if r["prom_punct"] is not None else
                     f"| {r['cell']} | {r['P_state']} | {r['prom_state']:.3f} | {r['P_tok']} | {r['prom_tok']:.3f} | — | — |")
        L.append("")
    out = ROOT / "docs/APPENDIX_SPECTRA.md"
    out.write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
